// Code generated from docs/protocol-method-inventory.md; DO NOT EDIT.
package protocol

var methodRegistry = []MethodInfo{
	{Method: "account/login/cancel", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:1002, typescript:ClientRequest.ts"},
	{Method: "account/login/start", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:995, typescript:ClientRequest.ts"},
	{Method: "account/logout", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:1008, typescript:ClientRequest.ts"},
	{Method: "account/rateLimitResetCredit/consume", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:1020, typescript:ClientRequest.ts"},
	{Method: "account/rateLimits/read", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:1014, typescript:ClientRequest.ts"},
	{Method: "account/read", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:1143, typescript:ClientRequest.ts"},
	{Method: "account/sendAddCreditsNudgeEmail", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:1038, typescript:ClientRequest.ts"},
	{Method: "account/usage/read", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:1026, typescript:ClientRequest.ts"},
	{Method: "account/workspaceMessages/read", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:1032, typescript:ClientRequest.ts"},
	{Method: "app/list", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:732, typescript:ClientRequest.ts"},
	{Method: "collaborationMode/list", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "protocol crate:common.rs:927"},
	{Method: "command/exec", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:1051, typescript:ClientRequest.ts"},
	{Method: "command/exec/resize", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:1070, typescript:ClientRequest.ts"},
	{Method: "command/exec/terminate", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:1064, typescript:ClientRequest.ts"},
	{Method: "command/exec/write", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:1058, typescript:ClientRequest.ts"},
	{Method: "config/batchWrite", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:1130, typescript:ClientRequest.ts"},
	{Method: "config/mcpServer/reload", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:960, typescript:ClientRequest.ts"},
	{Method: "config/read", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:1104, typescript:ClientRequest.ts"},
	{Method: "config/value/write", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:1124, typescript:ClientRequest.ts"},
	{Method: "configRequirements/read", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:1137, typescript:ClientRequest.ts"},
	{Method: "environment/add", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "protocol crate:common.rs:941"},
	{Method: "environment/info", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "protocol crate:common.rs:948"},
	{Method: "experimentalFeature/enablement/set", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:878, typescript:ClientRequest.ts"},
	{Method: "experimentalFeature/list", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:868, typescript:ClientRequest.ts"},
	{Method: "externalAgentConfig/detect", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:1109, typescript:ClientRequest.ts"},
	{Method: "externalAgentConfig/import", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:1114, typescript:ClientRequest.ts"},
	{Method: "externalAgentConfig/import/readHistories", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:1119, typescript:ClientRequest.ts"},
	{Method: "feedback/upload", Surface: SurfaceClientRequest, State: MethodNotApplicable, Source: "json schema:ClientRequest, protocol crate:common.rs:1044, typescript:ClientRequest.ts"},
	{Method: "fs/copy", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:769, typescript:ClientRequest.ts"},
	{Method: "fs/createDirectory", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:749, typescript:ClientRequest.ts"},
	{Method: "fs/getMetadata", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:754, typescript:ClientRequest.ts"},
	{Method: "fs/readDirectory", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:759, typescript:ClientRequest.ts"},
	{Method: "fs/readFile", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:739, typescript:ClientRequest.ts"},
	{Method: "fs/remove", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:764, typescript:ClientRequest.ts"},
	{Method: "fs/unwatch", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:779, typescript:ClientRequest.ts"},
	{Method: "fs/watch", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:774, typescript:ClientRequest.ts"},
	{Method: "fs/writeFile", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:744, typescript:ClientRequest.ts"},
	{Method: "fuzzyFileSearch", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, typescript:ClientRequest.ts"},
	{Method: "fuzzyFileSearch/sessionStart", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "protocol crate:common.rs:1174"},
	{Method: "fuzzyFileSearch/sessionStop", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "protocol crate:common.rs:1186"},
	{Method: "fuzzyFileSearch/sessionUpdate", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "protocol crate:common.rs:1180"},
	{Method: "getAuthStatus", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "typescript:ClientRequest.ts"},
	{Method: "getConversationSummary", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "typescript:ClientRequest.ts"},
	{Method: "gitDiffToRemote", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "typescript:ClientRequest.ts"},
	{Method: "hooks/list", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:667, typescript:ClientRequest.ts"},
	{Method: "initialize", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, typescript:ClientRequest.ts"},
	{Method: "marketplace/add", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:672, typescript:ClientRequest.ts"},
	{Method: "marketplace/remove", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:677, typescript:ClientRequest.ts"},
	{Method: "marketplace/upgrade", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:682, typescript:ClientRequest.ts"},
	{Method: "mcpServer/oauth/login", Surface: SurfaceClientRequest, State: MethodBlocked, Source: "json schema:ClientRequest, protocol crate:common.rs:954, typescript:ClientRequest.ts"},
	{Method: "mcpServer/resource/read", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:972, typescript:ClientRequest.ts"},
	{Method: "mcpServer/tool/call", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:978, typescript:ClientRequest.ts"},
	{Method: "mcpServerStatus/list", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:966, typescript:ClientRequest.ts"},
	{Method: "memory/reset", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "protocol crate:common.rs:567"},
	{Method: "mock/experimentalMethod", Surface: SurfaceClientRequest, State: MethodNotApplicable, Source: "protocol crate:common.rs:934"},
	{Method: "model/list", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:858, typescript:ClientRequest.ts"},
	{Method: "modelProvider/capabilities/read", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:863, typescript:ClientRequest.ts"},
	{Method: "permissionProfile/list", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:873, typescript:ClientRequest.ts"},
	{Method: "plugin/install", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:789, typescript:ClientRequest.ts"},
	{Method: "plugin/installed", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:692, typescript:ClientRequest.ts"},
	{Method: "plugin/list", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:687, typescript:ClientRequest.ts"},
	{Method: "plugin/read", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:697, typescript:ClientRequest.ts"},
	{Method: "plugin/share/checkout", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:722, typescript:ClientRequest.ts"},
	{Method: "plugin/share/delete", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:727, typescript:ClientRequest.ts"},
	{Method: "plugin/share/list", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:717, typescript:ClientRequest.ts"},
	{Method: "plugin/share/save", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:707, typescript:ClientRequest.ts"},
	{Method: "plugin/share/updateTargets", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:712, typescript:ClientRequest.ts"},
	{Method: "plugin/skill/read", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:702, typescript:ClientRequest.ts"},
	{Method: "plugin/uninstall", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:794, typescript:ClientRequest.ts"},
	{Method: "process/kill", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "protocol crate:common.rs:1091"},
	{Method: "process/resizePty", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "protocol crate:common.rs:1098"},
	{Method: "process/spawn", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "protocol crate:common.rs:1077"},
	{Method: "process/writeStdin", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "protocol crate:common.rs:1084"},
	{Method: "remoteControl/client/list", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "protocol crate:common.rs:914"},
	{Method: "remoteControl/client/revoke", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "protocol crate:common.rs:920"},
	{Method: "remoteControl/disable", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "protocol crate:common.rs:890"},
	{Method: "remoteControl/enable", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "protocol crate:common.rs:884"},
	{Method: "remoteControl/pairing/start", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "protocol crate:common.rs:902"},
	{Method: "remoteControl/pairing/status", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "protocol crate:common.rs:908"},
	{Method: "remoteControl/status/read", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "protocol crate:common.rs:896"},
	{Method: "review/start", Surface: SurfaceClientRequest, State: MethodBlocked, Source: "json schema:ClientRequest, protocol crate:common.rs:852, typescript:ClientRequest.ts"},
	{Method: "skills/config/write", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:784, typescript:ClientRequest.ts"},
	{Method: "skills/extraRoots/set", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:662, typescript:ClientRequest.ts"},
	{Method: "skills/list", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:657, typescript:ClientRequest.ts"},
	{Method: "thread/approveGuardianDeniedAction", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:587, typescript:ClientRequest.ts"},
	{Method: "thread/archive", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:494, typescript:ClientRequest.ts"},
	{Method: "thread/backgroundTerminals/clean", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "protocol crate:common.rs:593"},
	{Method: "thread/backgroundTerminals/list", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "protocol crate:common.rs:599"},
	{Method: "thread/backgroundTerminals/terminate", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "protocol crate:common.rs:605"},
	{Method: "thread/compact/start", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:577, typescript:ClientRequest.ts"},
	{Method: "thread/decrement_elicitation", Surface: SurfaceClientRequest, State: MethodBlocked, Source: "protocol crate:common.rs:523"},
	{Method: "thread/delete", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:499, typescript:ClientRequest.ts"},
	{Method: "thread/fork", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:488, typescript:ClientRequest.ts"},
	{Method: "thread/goal/clear", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:543, typescript:ClientRequest.ts"},
	{Method: "thread/goal/get", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:538, typescript:ClientRequest.ts"},
	{Method: "thread/goal/set", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:533, typescript:ClientRequest.ts"},
	{Method: "thread/increment_elicitation", Surface: SurfaceClientRequest, State: MethodBlocked, Source: "protocol crate:common.rs:514"},
	{Method: "thread/inject_items", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:652, typescript:ClientRequest.ts"},
	{Method: "thread/items/list", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "protocol crate:common.rs:645"},
	{Method: "thread/list", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:615, typescript:ClientRequest.ts"},
	{Method: "thread/loaded/list", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:627, typescript:ClientRequest.ts"},
	{Method: "thread/memoryMode/set", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "protocol crate:common.rs:561"},
	{Method: "thread/metadata/update", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:548, typescript:ClientRequest.ts"},
	{Method: "thread/name/set", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:528, typescript:ClientRequest.ts"},
	{Method: "thread/read", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:632, typescript:ClientRequest.ts"},
	{Method: "thread/realtime/appendAudio", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "protocol crate:common.rs:823"},
	{Method: "thread/realtime/appendSpeech", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "protocol crate:common.rs:835"},
	{Method: "thread/realtime/appendText", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "protocol crate:common.rs:829"},
	{Method: "thread/realtime/listVoices", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "protocol crate:common.rs:847"},
	{Method: "thread/realtime/start", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "protocol crate:common.rs:817"},
	{Method: "thread/realtime/stop", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "protocol crate:common.rs:841"},
	{Method: "thread/resume", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:482, typescript:ClientRequest.ts"},
	{Method: "thread/rollback", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:610, typescript:ClientRequest.ts"},
	{Method: "thread/search", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "protocol crate:common.rs:622"},
	{Method: "thread/settings/update", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "protocol crate:common.rs:554"},
	{Method: "thread/shellCommand", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:582, typescript:ClientRequest.ts"},
	{Method: "thread/start", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:476, typescript:ClientRequest.ts"},
	{Method: "thread/turns/list", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "protocol crate:common.rs:638"},
	{Method: "thread/unarchive", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:572, typescript:ClientRequest.ts"},
	{Method: "thread/unsubscribe", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:504, typescript:ClientRequest.ts"},
	{Method: "turn/interrupt", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:811, typescript:ClientRequest.ts"},
	{Method: "turn/start", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:799, typescript:ClientRequest.ts"},
	{Method: "turn/steer", Surface: SurfaceClientRequest, State: MethodImplemented, Source: "json schema:ClientRequest, protocol crate:common.rs:805, typescript:ClientRequest.ts"},
	{Method: "windowsSandbox/readiness", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:989, typescript:ClientRequest.ts"},
	{Method: "windowsSandbox/setupStart", Surface: SurfaceClientRequest, State: MethodDeferredStub, Source: "json schema:ClientRequest, protocol crate:common.rs:984, typescript:ClientRequest.ts"},
	{Method: "account/login/completed", Surface: SurfaceServerNotification, State: MethodDeferredStub, Source: "json schema:ServerNotification, typescript:ServerNotification.ts"},
	{Method: "account/rateLimits/updated", Surface: SurfaceServerNotification, State: MethodDeferredStub, Source: "json schema:ServerNotification, protocol crate:common.rs:1656, typescript:ServerNotification.ts"},
	{Method: "account/updated", Surface: SurfaceServerNotification, State: MethodDeferredStub, Source: "json schema:ServerNotification, protocol crate:common.rs:1655, typescript:ServerNotification.ts"},
	{Method: "app/list/updated", Surface: SurfaceServerNotification, State: MethodDeferredStub, Source: "json schema:ServerNotification, protocol crate:common.rs:1657, typescript:ServerNotification.ts"},
	{Method: "command/exec/outputDelta", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "json schema:ServerNotification, protocol crate:common.rs:1639, typescript:ServerNotification.ts"},
	{Method: "configWarning", Surface: SurfaceServerNotification, State: MethodBlocked, Source: "json schema:ServerNotification, protocol crate:common.rs:1675, typescript:ServerNotification.ts"},
	{Method: "deprecationNotice", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "json schema:ServerNotification, protocol crate:common.rs:1674, typescript:ServerNotification.ts"},
	{Method: "error", Surface: SurfaceServerNotification, State: MethodBlocked, Source: "json schema:ServerNotification, protocol crate:common.rs:1609, typescript:ServerNotification.ts"},
	{Method: "externalAgentConfig/import/completed", Surface: SurfaceServerNotification, State: MethodDeferredStub, Source: "json schema:ServerNotification, protocol crate:common.rs:1660, typescript:ServerNotification.ts"},
	{Method: "externalAgentConfig/import/progress", Surface: SurfaceServerNotification, State: MethodDeferredStub, Source: "json schema:ServerNotification, protocol crate:common.rs:1659, typescript:ServerNotification.ts"},
	{Method: "fs/changed", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "json schema:ServerNotification, protocol crate:common.rs:1661, typescript:ServerNotification.ts"},
	{Method: "fuzzyFileSearch/sessionCompleted", Surface: SurfaceServerNotification, State: MethodDeferredStub, Source: "json schema:ServerNotification, protocol crate:common.rs:1677, typescript:ServerNotification.ts"},
	{Method: "fuzzyFileSearch/sessionUpdated", Surface: SurfaceServerNotification, State: MethodDeferredStub, Source: "json schema:ServerNotification, protocol crate:common.rs:1676, typescript:ServerNotification.ts"},
	{Method: "guardianWarning", Surface: SurfaceServerNotification, State: MethodBlocked, Source: "json schema:ServerNotification, protocol crate:common.rs:1673, typescript:ServerNotification.ts"},
	{Method: "hook/completed", Surface: SurfaceServerNotification, State: MethodBlocked, Source: "json schema:ServerNotification, protocol crate:common.rs:1626, typescript:ServerNotification.ts"},
	{Method: "hook/started", Surface: SurfaceServerNotification, State: MethodBlocked, Source: "json schema:ServerNotification, protocol crate:common.rs:1624, typescript:ServerNotification.ts"},
	{Method: "item/agentMessage/delta", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "json schema:ServerNotification, protocol crate:common.rs:1635, typescript:ServerNotification.ts"},
	{Method: "item/autoApprovalReview/completed", Surface: SurfaceServerNotification, State: MethodBlocked, Source: "json schema:ServerNotification, protocol crate:common.rs:1631, typescript:ServerNotification.ts"},
	{Method: "item/autoApprovalReview/started", Surface: SurfaceServerNotification, State: MethodBlocked, Source: "json schema:ServerNotification, protocol crate:common.rs:1630, typescript:ServerNotification.ts"},
	{Method: "item/commandExecution/outputDelta", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "json schema:ServerNotification, protocol crate:common.rs:1646, typescript:ServerNotification.ts"},
	{Method: "item/commandExecution/terminalInteraction", Surface: SurfaceServerNotification, State: MethodBlocked, Source: "json schema:ServerNotification, protocol crate:common.rs:1647, typescript:ServerNotification.ts"},
	{Method: "item/completed", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "json schema:ServerNotification, protocol crate:common.rs:1632, typescript:ServerNotification.ts"},
	{Method: "item/fileChange/outputDelta", Surface: SurfaceServerNotification, State: MethodBlocked, Source: "json schema:ServerNotification, protocol crate:common.rs:1649, typescript:ServerNotification.ts"},
	{Method: "item/fileChange/patchUpdated", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "json schema:ServerNotification, protocol crate:common.rs:1650, typescript:ServerNotification.ts"},
	{Method: "item/mcpToolCall/progress", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "json schema:ServerNotification, protocol crate:common.rs:1652, typescript:ServerNotification.ts"},
	{Method: "item/plan/delta", Surface: SurfaceServerNotification, State: MethodBlocked, Source: "json schema:ServerNotification, protocol crate:common.rs:1637, typescript:ServerNotification.ts"},
	{Method: "item/reasoning/summaryPartAdded", Surface: SurfaceServerNotification, State: MethodBlocked, Source: "json schema:ServerNotification, protocol crate:common.rs:1663, typescript:ServerNotification.ts"},
	{Method: "item/reasoning/summaryTextDelta", Surface: SurfaceServerNotification, State: MethodBlocked, Source: "json schema:ServerNotification, protocol crate:common.rs:1662, typescript:ServerNotification.ts"},
	{Method: "item/reasoning/textDelta", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "json schema:ServerNotification, protocol crate:common.rs:1664, typescript:ServerNotification.ts"},
	{Method: "item/started", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "json schema:ServerNotification, protocol crate:common.rs:1629, typescript:ServerNotification.ts"},
	{Method: "mcpServer/oauthLogin/completed", Surface: SurfaceServerNotification, State: MethodBlocked, Source: "json schema:ServerNotification, protocol crate:common.rs:1653, typescript:ServerNotification.ts"},
	{Method: "mcpServer/startupStatus/updated", Surface: SurfaceServerNotification, State: MethodBlocked, Source: "json schema:ServerNotification, protocol crate:common.rs:1654, typescript:ServerNotification.ts"},
	{Method: "model/rerouted", Surface: SurfaceServerNotification, State: MethodBlocked, Source: "json schema:ServerNotification, protocol crate:common.rs:1667, typescript:ServerNotification.ts"},
	{Method: "model/safetyBuffering/updated", Surface: SurfaceServerNotification, State: MethodBlocked, Source: "json schema:ServerNotification, protocol crate:common.rs:1671, typescript:ServerNotification.ts"},
	{Method: "model/verification", Surface: SurfaceServerNotification, State: MethodBlocked, Source: "json schema:ServerNotification, protocol crate:common.rs:1668, typescript:ServerNotification.ts"},
	{Method: "process/exited", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "json schema:ServerNotification, protocol crate:common.rs:1645, typescript:ServerNotification.ts"},
	{Method: "process/outputDelta", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "json schema:ServerNotification, protocol crate:common.rs:1642, typescript:ServerNotification.ts"},
	{Method: "rawResponseItem/completed", Surface: SurfaceServerNotification, State: MethodBlocked, Source: "protocol crate:common.rs:1634, typescript:ServerNotification.ts"},
	{Method: "remoteControl/status/changed", Surface: SurfaceServerNotification, State: MethodDeferredStub, Source: "json schema:ServerNotification, protocol crate:common.rs:1658, typescript:ServerNotification.ts"},
	{Method: "serverRequest/resolved", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "json schema:ServerNotification, protocol crate:common.rs:1651, typescript:ServerNotification.ts"},
	{Method: "skills/changed", Surface: SurfaceServerNotification, State: MethodDeferredStub, Source: "json schema:ServerNotification, protocol crate:common.rs:1616, typescript:ServerNotification.ts"},
	{Method: "thread/archived", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "json schema:ServerNotification, protocol crate:common.rs:1612, typescript:ServerNotification.ts"},
	{Method: "thread/closed", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "json schema:ServerNotification, protocol crate:common.rs:1615, typescript:ServerNotification.ts"},
	{Method: "thread/compacted", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "json schema:ServerNotification, protocol crate:common.rs:1666, typescript:ServerNotification.ts"},
	{Method: "thread/deleted", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "json schema:ServerNotification, protocol crate:common.rs:1613, typescript:ServerNotification.ts"},
	{Method: "thread/goal/cleared", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "json schema:ServerNotification, protocol crate:common.rs:1619, typescript:ServerNotification.ts"},
	{Method: "thread/goal/updated", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "json schema:ServerNotification, protocol crate:common.rs:1618, typescript:ServerNotification.ts"},
	{Method: "thread/name/updated", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "json schema:ServerNotification, protocol crate:common.rs:1617, typescript:ServerNotification.ts"},
	{Method: "thread/realtime/closed", Surface: SurfaceServerNotification, State: MethodDeferredStub, Source: "json schema:ServerNotification, protocol crate:common.rs:1693, typescript:ServerNotification.ts"},
	{Method: "thread/realtime/error", Surface: SurfaceServerNotification, State: MethodDeferredStub, Source: "json schema:ServerNotification, protocol crate:common.rs:1691, typescript:ServerNotification.ts"},
	{Method: "thread/realtime/itemAdded", Surface: SurfaceServerNotification, State: MethodDeferredStub, Source: "json schema:ServerNotification, protocol crate:common.rs:1681, typescript:ServerNotification.ts"},
	{Method: "thread/realtime/outputAudio/delta", Surface: SurfaceServerNotification, State: MethodDeferredStub, Source: "json schema:ServerNotification, protocol crate:common.rs:1687, typescript:ServerNotification.ts"},
	{Method: "thread/realtime/sdp", Surface: SurfaceServerNotification, State: MethodDeferredStub, Source: "json schema:ServerNotification, protocol crate:common.rs:1689, typescript:ServerNotification.ts"},
	{Method: "thread/realtime/started", Surface: SurfaceServerNotification, State: MethodDeferredStub, Source: "json schema:ServerNotification, protocol crate:common.rs:1679, typescript:ServerNotification.ts"},
	{Method: "thread/realtime/transcript/delta", Surface: SurfaceServerNotification, State: MethodDeferredStub, Source: "json schema:ServerNotification, protocol crate:common.rs:1683, typescript:ServerNotification.ts"},
	{Method: "thread/realtime/transcript/done", Surface: SurfaceServerNotification, State: MethodDeferredStub, Source: "json schema:ServerNotification, protocol crate:common.rs:1685, typescript:ServerNotification.ts"},
	{Method: "thread/settings/updated", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "json schema:ServerNotification, protocol crate:common.rs:1621, typescript:ServerNotification.ts"},
	{Method: "thread/started", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "json schema:ServerNotification, protocol crate:common.rs:1610, typescript:ServerNotification.ts"},
	{Method: "thread/status/changed", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "json schema:ServerNotification, protocol crate:common.rs:1611, typescript:ServerNotification.ts"},
	{Method: "thread/tokenUsage/updated", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "json schema:ServerNotification, protocol crate:common.rs:1622, typescript:ServerNotification.ts"},
	{Method: "thread/unarchived", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "json schema:ServerNotification, protocol crate:common.rs:1614, typescript:ServerNotification.ts"},
	{Method: "turn/completed", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "json schema:ServerNotification, protocol crate:common.rs:1625, typescript:ServerNotification.ts"},
	{Method: "turn/diff/updated", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "json schema:ServerNotification, protocol crate:common.rs:1627, typescript:ServerNotification.ts"},
	{Method: "turn/moderationMetadata", Surface: SurfaceServerNotification, State: MethodBlocked, Source: "json schema:ServerNotification, protocol crate:common.rs:1670, typescript:ServerNotification.ts"},
	{Method: "turn/plan/updated", Surface: SurfaceServerNotification, State: MethodBlocked, Source: "json schema:ServerNotification, protocol crate:common.rs:1628, typescript:ServerNotification.ts"},
	{Method: "turn/started", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "json schema:ServerNotification, protocol crate:common.rs:1623, typescript:ServerNotification.ts"},
	{Method: "warning", Surface: SurfaceServerNotification, State: MethodBlocked, Source: "json schema:ServerNotification, protocol crate:common.rs:1672, typescript:ServerNotification.ts"},
	{Method: "windows/worldWritableWarning", Surface: SurfaceServerNotification, State: MethodDeferredStub, Source: "json schema:ServerNotification, protocol crate:common.rs:1696, typescript:ServerNotification.ts"},
	{Method: "windowsSandbox/setupCompleted", Surface: SurfaceServerNotification, State: MethodDeferredStub, Source: "json schema:ServerNotification, protocol crate:common.rs:1697, typescript:ServerNotification.ts"},
	{Method: "cache/benchmark/completed", Surface: SurfaceServerNotification, State: MethodImplemented, Source: "goal.txt"},
	{Method: "account/chatgptAuthTokens/refresh", Surface: SurfaceServerRequest, State: MethodDeferredStub, Source: "json schema:ServerRequest, protocol crate:common.rs:1492, typescript:ServerRequest.ts"},
	{Method: "applyPatchApproval", Surface: SurfaceServerRequest, State: MethodDeferredStub, Source: "json schema:ServerRequest, typescript:ServerRequest.ts"},
	{Method: "attestation/generate", Surface: SurfaceServerRequest, State: MethodBlocked, Source: "json schema:ServerRequest, protocol crate:common.rs:1498, typescript:ServerRequest.ts"},
	{Method: "currentTime/read", Surface: SurfaceServerRequest, State: MethodBlocked, Source: "protocol crate:common.rs:1505"},
	{Method: "execCommandApproval", Surface: SurfaceServerRequest, State: MethodDeferredStub, Source: "json schema:ServerRequest, typescript:ServerRequest.ts"},
	{Method: "item/commandExecution/requestApproval", Surface: SurfaceServerRequest, State: MethodImplemented, Source: "json schema:ServerRequest, protocol crate:common.rs:1456, typescript:ServerRequest.ts"},
	{Method: "item/fileChange/requestApproval", Surface: SurfaceServerRequest, State: MethodImplemented, Source: "json schema:ServerRequest, protocol crate:common.rs:1463, typescript:ServerRequest.ts"},
	{Method: "item/permissions/requestApproval", Surface: SurfaceServerRequest, State: MethodImplemented, Source: "json schema:ServerRequest, protocol crate:common.rs:1481, typescript:ServerRequest.ts"},
	{Method: "item/tool/call", Surface: SurfaceServerRequest, State: MethodImplemented, Source: "json schema:ServerRequest, protocol crate:common.rs:1487, typescript:ServerRequest.ts"},
	{Method: "item/tool/requestUserInput", Surface: SurfaceServerRequest, State: MethodImplemented, Source: "json schema:ServerRequest, protocol crate:common.rs:1469, typescript:ServerRequest.ts"},
	{Method: "mcpServer/elicitation/request", Surface: SurfaceServerRequest, State: MethodImplemented, Source: "json schema:ServerRequest, protocol crate:common.rs:1475, typescript:ServerRequest.ts"},
	{Method: "initialized", Surface: SurfaceClientNotification, State: MethodImplemented, Source: "json schema:ClientNotification, typescript:ClientNotification.ts"},
	{Method: "approval/respond", Surface: SurfaceGollemExtension, State: MethodImplemented, Source: "goal.txt"},
	{Method: "cache/benchmark", Surface: SurfaceGollemExtension, State: MethodImplemented, Source: "goal.txt"},
	{Method: "cache/stats", Surface: SurfaceGollemExtension, State: MethodImplemented, Source: "goal.txt"},
	{Method: "daemon/restart", Surface: SurfaceGollemExtension, State: MethodImplemented, Source: "goal.txt"},
	{Method: "daemon/start", Surface: SurfaceGollemExtension, State: MethodImplemented, Source: "goal.txt"},
	{Method: "daemon/status", Surface: SurfaceGollemExtension, State: MethodImplemented, Source: "goal.txt"},
	{Method: "daemon/stop", Surface: SurfaceGollemExtension, State: MethodImplemented, Source: "goal.txt"},
	{Method: "daemon/version", Surface: SurfaceGollemExtension, State: MethodImplemented, Source: "goal.txt"},
	{Method: "git/commit", Surface: SurfaceGollemExtension, State: MethodImplemented, Source: "goal.txt"},
	{Method: "git/diff", Surface: SurfaceGollemExtension, State: MethodImplemented, Source: "goal.txt"},
	{Method: "git/status", Surface: SurfaceGollemExtension, State: MethodImplemented, Source: "goal.txt"},
	{Method: "git/worktree/create", Surface: SurfaceGollemExtension, State: MethodImplemented, Source: "goal.txt"},
	{Method: "git/worktree/list", Surface: SurfaceGollemExtension, State: MethodImplemented, Source: "goal.txt"},
	{Method: "provider/capabilities/read", Surface: SurfaceGollemExtension, State: MethodImplemented, Source: "goal.txt"},
	{Method: "provider/list", Surface: SurfaceGollemExtension, State: MethodImplemented, Source: "goal.txt"},
	{Method: "tool/list", Surface: SurfaceGollemExtension, State: MethodImplemented, Source: "goal.txt"},
	{Method: "turn/retry", Surface: SurfaceGollemExtension, State: MethodImplemented, Source: "goal.txt"},
}

var methodIndex = buildMethodIndex()

func buildMethodIndex() map[string]MethodInfo {
	index := make(map[string]MethodInfo, len(methodRegistry))
	for _, info := range methodRegistry {
		if _, exists := index[info.Method]; !exists {
			index[info.Method] = info
		}
	}
	return index
}
