package protocol

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"slices"
	"sort"
	"strings"
	"unicode"
)

const typeScriptOptionalNonNullKeyword = "x-gollem-typescript-optional-nonnull"
const typeScriptBigIntKeyword = "x-gollem-typescript-bigint"
const typeScriptRawTypeKeyword = "x-gollem-typescript-raw-type"

const typeScriptGeneratedHeader = "// Code generated by go generate ./appserver/protocol; DO NOT EDIT.\n\n"

// MarshalTypeScript generates the TypeScript binding for the current public
// app-server schema and binding metadata.
func MarshalTypeScript() ([]byte, error) {
	schema := JSONSchema()
	defs, ok := schema["$defs"].(Schema)
	if !ok {
		return nil, fmt.Errorf("protocol schema definitions have type %T", schema["$defs"])
	}

	var out bytes.Buffer
	out.WriteString(typeScriptGeneratedHeader)
	fmt.Fprintf(&out, "export const protocolVersion = %s as const;\n", typeScriptString(ProtocolVersion))
	fmt.Fprintf(&out, "export const schemaVersion = %s as const;\n\n", typeScriptString(SchemaVersion))
	writeTypeScriptProtocolMetadata(&out)

	names := make([]string, 0, len(defs))
	for name := range defs {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		definition := defs[name]
		if name == "ClientRequest" || name == "ServerNotification" {
			contract := clientRequestEnvelopeContract
			includeTimestamp := false
			if name == "ServerNotification" {
				contract = serverNotificationEnvelopeContract
				includeTimestamp = true
			}
			rawType, err := topLevelEnvelopeTypeScript(contract, includeTimestamp)
			if err != nil {
				return nil, err
			}
			definition = Schema{typeScriptRawTypeKeyword: rawType}
		}
		if name == "Account" || name == "AccountLoginCompletedNotification" || name == "AccountRateLimitsUpdatedNotification" ||
			name == "AccountUpdatedNotification" ||
			name == "AccountTokenUsageSummary" ||
			name == "AppBranding" || name == "AppConfig" || name == "AppInfo" || name == "AppMetadata" || name == "AppScreenshot" ||
			name == "AppSummary" || name == "AppTemplateSummary" || name == "AppsDefaultConfig" ||
			name == "AppsListParams" || name == "AppsListResponse" ||
			name == "AppToolConfig" ||
			name == "ApplyPatchApprovalParams" ||
			name == "AttestationGenerateParams" ||
			name == "ChatgptAuthTokensRefreshResponse" ||
			name == "ConsumeAccountRateLimitResetCreditParams" ||
			name == "ConsumeAccountRateLimitResetCreditResponse" || name == "CreditsSnapshot" ||
			name == "GetAccountParams" || name == "GetAccountRateLimitsResponse" || name == "GetAccountResponse" ||
			name == "GetAccountTokenUsageParams" || name == "GetAccountTokenUsageResponse" || name == "GetWorkspaceMessagesResponse" ||
			name == "EnvironmentConnectionNotification" || name == "SkillsChangedNotification" ||
			name == "ThreadQueueChangedNotification" || name == "ThreadRevertedNotification" ||
			name == "RemoteControlStatusChangedNotification" ||
			name == "WindowsSandboxSetupCompletedNotification" || name == "WindowsWorldWritableWarningNotification" ||
			name == "ThreadRealtimeAudioChunk" || name == "ThreadRealtimeClosedNotification" ||
			name == "ThreadRealtimeErrorNotification" || name == "ThreadRealtimeItemAddedNotification" ||
			name == "ThreadRealtimeOutputAudioDeltaNotification" || name == "ThreadRealtimeSdpNotification" ||
			name == "ThreadRealtimeStartedNotification" || name == "ThreadRealtimeTranscriptDeltaNotification" ||
			name == "ThreadRealtimeTranscriptDoneNotification" ||
			name == "MigrationDetails" ||
			name == "ExternalAgentConfigMigrationItem" ||
			name == "ExternalAgentConfigImportItemTypeFailure" ||
			name == "ExternalAgentConfigImportItemTypeSuccess" ||
			name == "ExecCommandApprovalParams" ||
			name == "ExperimentalFeature" || name == "ExperimentalFeatureEnablementSetParams" ||
			name == "ExperimentalFeatureEnablementSetResponse" || name == "ExperimentalFeatureListParams" ||
			name == "ExperimentalFeatureListResponse" ||
			name == "FuzzyFileSearchParams" || name == "FuzzyFileSearchResult" ||
			name == "HookRunSummary" || name == "HookStartedNotification" ||
			name == "HookCompletedNotification" || name == "HookMetadata" ||
			name == "GuardianApprovalReview" || name == "ParsedCommand" ||
			name == "ProcessExitedNotification" || name == "ProcessOutputDeltaNotification" ||
			name == "ProcessTerminalSize" ||
			name == "PermissionsRequestApprovalParams" ||
			name == "RateLimitResetCredit" || name == "RateLimitResetCreditsSummary" ||
			name == "RateLimitSnapshot" || name == "RateLimitWindow" ||
			name == "SendAddCreditsNudgeEmailParams" || name == "SendAddCreditsNudgeEmailResponse" ||
			name == "SpendControlLimitSnapshot" ||
			name == "WorkspaceMessage" ||
			name == "ItemGuardianApprovalReviewCompletedNotification" ||
			name == "ItemGuardianApprovalReviewStartedNotification" {
			// Rust accepts omitted serde default/Option fields while generated
			// TypeScript requires callers to provide their canonical values.
			schema, _ := typeScriptSchema(definition)
			renderSchema := make(Schema, len(schema)+1)
			for key, value := range schema {
				renderSchema[key] = value
			}
			schema = renderSchema
			switch name {
			case "Account":
				// ts-rs requires the defaulted Bedrock credential source even
				// though serde accepts its omission.
				variants := schema["oneOf"].([]any)
				for _, rawVariant := range variants {
					rawVariant.(Schema)["x-gollem-typescript-ignore-additional-properties"] = true
				}
				variants[1].(Schema)["properties"].(Schema)["email"] = nullableStringSchema()
				bedrock := variants[2].(Schema)
				bedrock["required"] = []string{"credentialSource", "type"}
				bedrock["properties"].(Schema)["credentialSource"] = Schema{
					"$ref": "#/$defs/AmazonBedrockCredentialSource",
				}
			case "AccountLoginCompletedNotification":
				schema["required"] = []string{"loginId", "success", "error"}
			case "AccountRateLimitsUpdatedNotification":
				schema["required"] = []string{"rateLimits"}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "AccountTokenUsageSummary":
				schema["required"] = []string{
					"lifetimeTokens", "peakDailyTokens", "longestRunningTurnSec",
					"currentStreakDays", "longestStreakDays",
				}
			case "AccountUpdatedNotification":
				schema["required"] = []string{"authMode", "planType"}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "AppBranding":
				schema["required"] = []string{
					"category", "developer", "website", "privacyPolicy", "termsOfService", "isDiscoverableApp",
				}
			case "AppConfig":
				schema["required"] = []string{
					"enabled", "approvals_reviewer", "destructive_enabled", "open_world_enabled",
					"default_tools_approval_mode", "default_tools_enabled", "tools",
				}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "AppInfo":
				schema["required"] = []string{
					"id", "name", "description", "logoUrl", "logoUrlDark", "iconAssets",
					"iconDarkAssets", "distributionChannel", "branding", "appMetadata", "labels",
					"installUrl", "isAccessible", "isEnabled", "pluginDisplayNames",
				}
			case "AppMetadata":
				schema["required"] = []string{
					"review", "categories", "subCategories", "seoDescription", "screenshots", "developer",
					"version", "versionId", "versionNotes", "firstPartyType",
					"firstPartyRequiresInstall", "showInComposerWhenUnlinked",
				}
			case "AppScreenshot":
				schema["required"] = []string{"url", "fileId", "userPrompt"}
			case "AppSummary":
				schema["required"] = []string{"id", "name", "description", "installUrl", "category"}
			case "AppTemplateSummary":
				schema["required"] = []string{
					"templateId", "name", "description", "category", "canonicalConnectorId",
					"logoUrl", "logoUrlDark", "materializedAppIds", "reason",
				}
			case "AppToolConfig":
				schema["required"] = []string{"enabled", "approval_mode"}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "AppsDefaultConfig":
				schema["required"] = []string{
					"enabled", "approvals_reviewer", "destructive_enabled", "open_world_enabled",
					"default_tools_approval_mode",
				}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "AppsListParams":
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "AppsListResponse":
				schema["required"] = []string{"data", "nextCursor"}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "ApplyPatchApprovalParams":
				schema["required"] = []string{
					"conversationId", "callId", "fileChanges", "reason", "grantRoot",
				}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "AttestationGenerateParams":
				// The source JSON Schema is open for serde compatibility while ts-rs
				// exports the exact empty Rust record.
				schema["additionalProperties"] = false
			case "CommandExecutionRequestApprovalParams":
				schema["required"] = []string{"threadId", "turnId", "itemId", "startedAtMs", "environmentId"}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "FileChangeRequestApprovalParams":
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "PermissionsRequestApprovalParams":
				schema["required"] = []string{
					"threadId", "turnId", "itemId", "environmentId", "startedAtMs", "cwd", "reason", "permissions",
				}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "ChatgptAuthTokensRefreshParams":
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "ChatgptAuthTokensRefreshResponse":
				schema["required"] = []string{
					"accessToken", "chatgptAccountId", "chatgptPlanType",
				}
			case "ConsumeAccountRateLimitResetCreditParams":
				schema["required"] = []string{"idempotencyKey"}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "ConsumeAccountRateLimitResetCreditResponse":
				schema["required"] = []string{"outcome"}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "CreditsSnapshot":
				schema["required"] = []string{"balance", "hasCredits", "unlimited"}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "GetAccountRateLimitsResponse":
				schema["required"] = []string{
					"rateLimitResetCredits", "rateLimits", "rateLimitsByLimitId",
				}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "GetAccountParams":
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "GetAccountResponse":
				schema["required"] = []string{"account", "requiresOpenaiAuth"}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "GetAccountTokenUsageParams":
				schema["x-gollem-typescript-ignore-additional-properties"] = true
				schema["properties"].(Schema)["threadId"] = nullableStringSchema()
			case "EnvironmentConnectionNotification", "ThreadQueueChangedNotification", "ThreadRevertedNotification", "WindowsWorldWritableWarningNotification":
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "SkillsChangedNotification":
				schema["additionalProperties"] = false
			case "RemoteControlStatusChangedNotification":
				schema["required"] = []string{"environmentId", "installationId", "serverName", "status"}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
				schema["properties"].(Schema)["environmentId"] = nullableStringSchema()
			case "GetAccountTokenUsageResponse":
				schema["required"] = []string{"dailyUsageBuckets", "summary"}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
				schema["properties"].(Schema)["dailyUsageBuckets"] = Schema{"anyOf": []any{
					Schema{"type": "array", "items": Schema{"$ref": "#/$defs/AccountTokenUsageDailyBucket"}},
					Schema{"type": "null"},
				}}
			case "WindowsSandboxSetupCompletedNotification":
				schema["required"] = []string{"error", "mode", "success"}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
				schema["properties"].(Schema)["error"] = nullableStringSchema()
			case "ThreadRealtimeAudioChunk":
				schema["required"] = []string{"data", "itemId", "numChannels", "sampleRate", "samplesPerChannel"}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
				properties := schema["properties"].(Schema)
				properties["itemId"] = nullableStringSchema()
				properties["samplesPerChannel"] = nullableIntegerSchema()
			case "ThreadRealtimeClosedNotification":
				schema["required"] = []string{"reason", "threadId"}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
				schema["properties"].(Schema)["reason"] = nullableStringSchema()
			case "ThreadRealtimeErrorNotification", "ThreadRealtimeOutputAudioDeltaNotification", "ThreadRealtimeSdpNotification", "ThreadRealtimeTranscriptDeltaNotification", "ThreadRealtimeTranscriptDoneNotification":
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "ThreadRealtimeItemAddedNotification":
				schema["x-gollem-typescript-ignore-additional-properties"] = true
				schema["properties"].(Schema)["item"] = Schema{"$ref": "#/$defs/JsonValue"}
			case "ThreadRealtimeStartedNotification":
				schema["required"] = []string{"realtimeSessionId", "threadId", "version"}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
				schema["properties"].(Schema)["realtimeSessionId"] = nullableStringSchema()
			case "GetWorkspaceMessagesResponse":
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "ExecCommandApprovalParams":
				schema["required"] = []string{
					"conversationId", "callId", "approvalId", "command", "cwd", "reason", "parsedCmd",
				}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "ExperimentalFeature":
				schema["required"] = []string{
					"announcement", "defaultEnabled", "description", "displayName", "enabled", "name", "stage",
				}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
				properties := schema["properties"].(Schema)
				properties["announcement"] = nullableStringSchema()
				properties["description"] = nullableStringSchema()
				properties["displayName"] = nullableStringSchema()
				properties["stage"] = Schema{"$ref": "#/$defs/ExperimentalFeatureStage"}
			case "ExperimentalFeatureListResponse":
				schema["required"] = []string{"data", "nextCursor"}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
				schema["properties"].(Schema)["nextCursor"] = nullableStringSchema()
			case "ExperimentalFeatureListParams":
				schema["x-gollem-typescript-ignore-additional-properties"] = true
				properties := schema["properties"].(Schema)
				properties["cursor"] = nullableStringSchema()
				properties["limit"] = nullableIntegerSchema()
				properties["threadId"] = nullableStringSchema()
			case "ExperimentalFeatureEnablementSetParams", "ExperimentalFeatureEnablementSetResponse":
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "MigrationDetails":
				schema["required"] = []string{
					"plugins", "skills", "sessions", "mcpServers", "hooks", "subagents", "commands",
				}
			case "ExternalAgentConfigMigrationItem":
				schema["required"] = []string{"itemType", "description", "cwd", "details"}
			case "ExternalAgentConfigImportItemTypeFailure":
				schema["required"] = []string{
					"itemType", "errorType", "failureStage", "message", "cwd", "source",
				}
			case "ExternalAgentConfigImportItemTypeSuccess":
				schema["required"] = []string{"itemType", "cwd", "source", "target"}
			case "FuzzyFileSearchParams":
				schema["required"] = []string{"query", "roots", "cancellationToken"}
			case "FuzzyFileSearchResult":
				schema["required"] = []string{
					"root", "path", "match_type", "file_name", "score", "indices",
				}
			case "HookRunSummary":
				schema["required"] = []string{
					"id", "eventName", "handlerType", "executionMode", "scope", "sourcePath",
					"source", "displayOrder", "status", "statusMessage", "startedAt",
					"completedAt", "durationMs", "entries",
				}
			case "HookStartedNotification", "HookCompletedNotification":
				schema["required"] = []string{"threadId", "turnId", "run"}
			case "HookMetadata":
				schema["required"] = []string{
					"key", "eventName", "handlerType", "matcher", "command", "timeoutSec",
					"statusMessage", "sourcePath", "source", "pluginId", "displayOrder",
					"enabled", "isManaged", "currentHash", "trustStatus",
				}
			case "GuardianApprovalReview":
				schema["required"] = []string{
					"status", "riskLevel", "userAuthorization", "rationale",
				}
			case "ParsedCommand":
				variants := schema["oneOf"].([]any)
				for index, required := range [][]string{
					{"type", "cmd", "name", "path"},
					{"type", "cmd", "path"},
					{"type", "cmd", "query", "path"},
					{"type", "cmd"},
				} {
					variant := variants[index].(Schema)
					copy := make(Schema, len(variant))
					for key, value := range variant {
						copy[key] = value
					}
					copy["required"] = required
					variants[index] = copy
				}
			case "ProcessExitedNotification", "ProcessOutputDeltaNotification", "ProcessTerminalSize":
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "RateLimitResetCredit":
				schema["required"] = []string{
					"description", "expiresAt", "grantedAt", "id", "resetType", "status", "title",
				}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "RateLimitResetCreditsSummary":
				schema["required"] = []string{"availableCount", "credits"}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "RateLimitSnapshot":
				schema["required"] = []string{
					"credits", "individualLimit", "limitId", "limitName", "planType",
					"primary", "rateLimitReachedType", "secondary",
				}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "RateLimitWindow":
				schema["required"] = []string{"resetsAt", "usedPercent", "windowDurationMins"}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "SendAddCreditsNudgeEmailParams", "SendAddCreditsNudgeEmailResponse":
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "SpendControlLimitSnapshot":
				schema["required"] = []string{"limit", "remainingPercent", "resetsAt", "used"}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
			case "WorkspaceMessage":
				schema["required"] = []string{
					"archivedAt", "createdAt", "messageBody", "messageId", "messageType",
				}
				schema["x-gollem-typescript-ignore-additional-properties"] = true
				schema["properties"].(Schema)["archivedAt"] = nullableIntegerSchema()
				schema["properties"].(Schema)["createdAt"] = nullableIntegerSchema()
			case "ItemGuardianApprovalReviewCompletedNotification":
				schema["required"] = []string{
					"threadId", "turnId", "startedAtMs", "completedAtMs", "reviewId",
					"targetItemId", "decisionSource", "review", "action",
				}
			case "ItemGuardianApprovalReviewStartedNotification":
				schema["required"] = []string{
					"threadId", "turnId", "startedAtMs", "reviewId", "targetItemId", "review", "action",
				}
			}
			definition = schema
		}
		if name == "ApplyPatchApprovalParams" {
			// ts-rs models HashMap values with optional mapped keys. Keep this
			// render-only hint out of the exact public JSON Schema.
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"fileChanges": Schema{
					"type":                             "object",
					"additionalProperties":             Schema{"$ref": "#/$defs/FileChange"},
					"x-gollem-typescript-optional-map": true,
				},
			})
		}
		switch name {
		case "Resource", "ResourceTemplate", "Tool", "McpServerStatus", "ListMcpServerStatusResponse":
			definition = mcpServerStatusTypeScriptDefinition(name, definition)
		}
		if name == "AppToolConfig" {
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"enabled": nullableBooleanSchema(),
			})
		}
		if name == "AppConfig" {
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"default_tools_enabled": nullableBooleanSchema(),
				"destructive_enabled":   nullableBooleanSchema(),
				"open_world_enabled":    nullableBooleanSchema(),
			})
		}
		if name == "AppToolsConfig" {
			// ts-rs flattens this HashMap and inlines AppToolConfig in an
			// optional mapped type. Keep the render-only shape out of the
			// intentionally open upstream JSON Schema.
			definition = Schema{
				"type": "object",
				"additionalProperties": Schema{
					"type": "object",
					"properties": Schema{
						"approval_mode": nullableSchemaRef("AppToolApproval"),
						"enabled":       nullableBooleanSchema(),
					},
					"required": []string{"enabled", "approval_mode"},
					"x-gollem-typescript-ignore-additional-properties": true,
				},
				"x-gollem-typescript-optional-map": true,
			}
		}
		if name == "AppsConfig" {
			// ts-rs intersects the required reserved default with an optional
			// flattened map of canonical app records. Keep this render-only
			// structure out of the intentionally open upstream JSON Schema.
			definition = Schema{
				"type": "object",
				"properties": Schema{
					"_default": nullableSchemaRef("AppsDefaultConfig"),
				},
				"required":                         []string{"_default"},
				"additionalProperties":             Schema{"$ref": "#/$defs/AppConfig"},
				"x-gollem-typescript-optional-map": true,
			}
		}
		if name == "AppsListParams" {
			// The pinned schema uses JSON Schema type arrays for nullable fields;
			// normalize only the render copy into unions understood by this renderer.
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"cursor":   nullableStringSchema(),
				"limit":    nullableIntegerSchema(),
				"threadId": nullableStringSchema(),
			})
		}
		if name == "AppsListResponse" {
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"nextCursor": nullableStringSchema(),
			})
		}
		if name == "CommandExecutionRequestApprovalParams" {
			schema, _ := typeScriptSchema(definition)
			schema["required"] = []string{"threadId", "turnId", "itemId", "startedAtMs", "environmentId"}
			schema["x-gollem-typescript-ignore-additional-properties"] = true
			definition = typeScriptDefinitionWithPropertySchemas(schema, Schema{
				"approvalId": nullableStringSchema(),
				"command":    nullableStringSchema(),
				"commandActions": Schema{"anyOf": []any{
					Schema{"type": "array", "items": Schema{"$ref": "#/$defs/CommandAction"}},
					Schema{"type": "null"},
				}},
				"environmentId": nullableStringSchema(),
				"proposedExecpolicyAmendment": Schema{"anyOf": []any{
					Schema{"type": "array", "items": Schema{"type": "string"}},
					Schema{"type": "null"},
				}},
				"proposedNetworkPolicyAmendments": Schema{"anyOf": []any{
					Schema{"type": "array", "items": Schema{"$ref": "#/$defs/NetworkPolicyAmendment"}},
					Schema{"type": "null"},
				}},
				"reason": nullableStringSchema(),
			})
		}
		if name == "FileChangeRequestApprovalParams" {
			schema, _ := typeScriptSchema(definition)
			schema["x-gollem-typescript-ignore-additional-properties"] = true
			definition = typeScriptDefinitionWithPropertySchemas(schema, Schema{
				"grantRoot": nullableStringSchema(),
				"reason":    nullableStringSchema(),
			})
		}
		if name == "PermissionsRequestApprovalParams" {
			// The source schema expresses nullable Options as JSON Schema type
			// arrays. Normalize only the renderer copy to the ts-rs union shape.
			schema, _ := typeScriptSchema(definition)
			schema["required"] = []string{
				"threadId", "turnId", "itemId", "environmentId", "startedAtMs", "cwd", "reason", "permissions",
			}
			schema["x-gollem-typescript-ignore-additional-properties"] = true
			definition = typeScriptDefinitionWithPropertySchemas(schema, Schema{
				"environmentId": nullableStringSchema(),
				"reason":        nullableStringSchema(),
			})
		}
		if name == "ToolRequestUserInputParams" {
			// The source schema expresses the deprecated optional timeout as a
			// type array, while ts-rs exports a required nullable number.
			schema, _ := typeScriptSchema(definition)
			schema["required"] = []string{"threadId", "turnId", "itemId", "questions", "isBlocking", "autoResolutionMs"}
			schema["x-gollem-typescript-ignore-additional-properties"] = true
			definition = typeScriptDefinitionWithPropertySchemas(schema, Schema{
				"autoResolutionMs": nullableIntegerSchema(),
			})
		}
		if name == "ToolRequestUserInputQuestion" {
			// serde defaults these fields, while ts-rs requires their canonical
			// serialized values. Preserve that distinction in the render copy.
			schema, _ := typeScriptSchema(definition)
			schema["required"] = []string{"id", "header", "question", "isOther", "isSecret", "options"}
			schema["x-gollem-typescript-ignore-additional-properties"] = true
			definition = typeScriptDefinitionWithPropertySchemas(schema, Schema{
				"options": nullableArrayRef("ToolRequestUserInputOption"),
			})
		}
		if name == "ToolRequestUserInputOption" || name == "ToolRequestUserInputAnswer" || name == "ToolRequestUserInputResponse" {
			schema, _ := typeScriptSchema(definition)
			schema["x-gollem-typescript-ignore-additional-properties"] = true
			definition = schema
		}
		if name == "ChatgptAuthTokensRefreshParams" {
			schema, _ := typeScriptSchema(definition)
			schema["x-gollem-typescript-ignore-additional-properties"] = true
			definition = typeScriptDefinitionWithPropertySchemas(schema, Schema{
				"previousAccountId": nullableStringSchema(),
			})
		}
		if name == "ApplyPatchApprovalParams" {
			schema, _ := typeScriptSchema(definition)
			schema["required"] = []string{"conversationId", "callId", "fileChanges", "reason", "grantRoot"}
			schema["x-gollem-typescript-ignore-additional-properties"] = true
			definition = typeScriptDefinitionWithPropertySchemas(schema, Schema{"grantRoot": nullableStringSchema(), "reason": nullableStringSchema()})
		}
		if name == "ExecCommandApprovalParams" {
			schema, _ := typeScriptSchema(definition)
			schema["required"] = []string{"conversationId", "callId", "approvalId", "command", "cwd", "reason", "parsedCmd"}
			schema["x-gollem-typescript-ignore-additional-properties"] = true
			definition = typeScriptDefinitionWithPropertySchemas(schema, Schema{"approvalId": nullableStringSchema(), "reason": nullableStringSchema()})
		}
		if name == "CommandExecParams" {
			// The source schema allows forward-compatible fields while ts-rs emits
			// a closed Rust record. Normalize nullable JSON Schema type arrays and
			// HashMap value semantics only in the TypeScript render copy.
			schema, _ := typeScriptSchema(definition)
			schema["x-gollem-typescript-ignore-additional-properties"] = true
			definition = typeScriptDefinitionWithPropertySchemas(schema, Schema{
				"cwd":            nullableStringSchema(),
				"env":            Schema{"anyOf": []any{Schema{"type": "object", "additionalProperties": Schema{"anyOf": []any{Schema{"type": "string"}, Schema{"type": "null"}}}, "x-gollem-typescript-optional-map": true}, Schema{"type": "null"}}},
				"outputBytesCap": Schema{"anyOf": []any{Schema{"type": "integer"}, Schema{"type": "null"}}},
				"processId":      nullableStringSchema(),
				"sandboxPolicy":  nullableSchemaRef("SandboxPolicy"),
				"size":           nullableSchemaRef("CommandExecTerminalSize"),
				"timeoutMs":      Schema{"anyOf": []any{Schema{"type": "integer"}, Schema{"type": "null"}}},
			})
		}
		if name == "CommandExecResponse" {
			// The source schema permits extension properties while ts-rs emits a
			// closed Rust record.
			schema, _ := typeScriptSchema(definition)
			schema["x-gollem-typescript-ignore-additional-properties"] = true
			definition = schema
		}
		if name == "SandboxPolicy" {
			// serde defaults these fields, but ts-rs presents the canonical output
			// shape with every field explicit. Preserve that render-only contract.
			schema, _ := typeScriptSchema(definition)
			variants := schema["oneOf"].([]any)
			for _, rawVariant := range variants {
				variant := rawVariant.(Schema)
				variant["x-gollem-typescript-ignore-additional-properties"] = true
				properties := variant["properties"].(Schema)
				if typeValues, ok := properties["type"].(Schema)["enum"].([]any); ok && len(typeValues) == 1 && typeValues[0] == "externalSandbox" {
					properties["networkAccess"] = Schema{"$ref": "#/$defs/NetworkAccess"}
				}
				required := []string{"type"}
				for _, field := range []string{"writableRoots", "networkAccess", "excludeTmpdirEnvVar", "excludeSlashTmp"} {
					if _, ok := properties[field]; ok {
						required = append(required, field)
					}
				}
				variant["required"] = required
			}
			definition = schema
		}
		if name == "ProcessOutputDeltaNotification" {
			// The exact schema wraps the stream reference in allOf to attach its
			// description. Render that property as the referenced Rust type.
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"stream": Schema{"$ref": "#/$defs/ProcessOutputStream"},
			})
		}
		if name == "RateLimitWindow" {
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"resetsAt": nullableIntegerSchema(), "windowDurationMins": nullableIntegerSchema(),
			})
		}
		if name == "CreditsSnapshot" {
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"balance": nullableStringSchema(),
			})
		}
		if name == "RateLimitSnapshot" {
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"limitId": nullableStringSchema(), "limitName": nullableStringSchema(),
			})
		}
		if name == "RateLimitResetCredit" {
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"description": nullableStringSchema(),
				"expiresAt":   nullableIntegerSchema(),
				"title":       nullableStringSchema(),
			})
		}
		if name == "RateLimitResetCreditsSummary" {
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"credits": Schema{"anyOf": []any{
					Schema{"type": "array", "items": Schema{"$ref": "#/$defs/RateLimitResetCredit"}},
					Schema{"type": "null"},
				}},
			})
			definition = typeScriptDefinitionWithBigIntProperties(definition, "availableCount")
		}
		if name == "GetAccountRateLimitsResponse" {
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"rateLimits": Schema{"$ref": "#/$defs/RateLimitSnapshot"},
				"rateLimitsByLimitId": Schema{"anyOf": []any{
					Schema{
						"type": "object", "additionalProperties": Schema{"$ref": "#/$defs/RateLimitSnapshot"},
						"x-gollem-typescript-optional-map": true,
					},
					Schema{"type": "null"},
				}},
			})
		}
		if name == "ConsumeAccountRateLimitResetCreditParams" {
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"creditId": nullableStringSchema(),
			})
		}
		if name == "AppInfo" {
			// ts-rs models HashMap values with optional mapped keys. Apply the
			// hint only to TypeScript rendering, not the exact public schema.
			nullableStringMap := Schema{"anyOf": []any{
				Schema{
					"type": "object", "additionalProperties": Schema{"type": "string"},
					"x-gollem-typescript-optional-map": true,
				},
				Schema{"type": "null"},
			}}
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"iconAssets": nullableStringMap, "iconDarkAssets": nullableStringMap,
				"labels": nullableStringMap,
			})
		}
		if name == "ExternalAgentConfigImportHistory" {
			// ts-rs maps this Rust i64 to bigint. Apply the hint only to a
			// render copy so the public JSON Schema remains exact.
			definition = typeScriptDefinitionWithBigIntProperties(definition, "completedAtMs")
		}
		if name == "AccountTokenUsageDailyBucket" {
			// ts-rs maps this Rust i64 to bigint. Keep the render hint out of
			// the exact public JSON Schema.
			definition = typeScriptDefinitionWithBigIntProperties(definition, "tokens")
		}
		if name == "AccountTokenUsageSummary" {
			// ts-rs maps every optional Rust i64 to required nullable bigint.
			// Keep the render hints out of the exact public JSON Schema.
			definition = typeScriptDefinitionWithBigIntProperties(
				definition, "lifetimeTokens", "peakDailyTokens", "longestRunningTurnSec",
				"currentStreakDays", "longestStreakDays",
			)
		}
		if name == "McpServerOauthLoginParams" {
			// ts-rs maps the optional Rust i64 timeout to nullable bigint.
			// Keep the render hint out of the exact public JSON Schema.
			definition = typeScriptDefinitionWithBigIntProperties(definition, "timeoutSecs")
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"scopes": Schema{"anyOf": []any{
					Schema{"type": "array", "items": Schema{"type": "string"}},
					Schema{"type": "null"},
				}},
				"threadId": Schema{"anyOf": []any{
					Schema{"type": "string"}, Schema{"type": "null"},
				}},
			})
		}
		if name == "McpServerOauthLoginCompletedNotification" {
			// ts-rs requires the nullable thread id while rendering the
			// skip-serialized error as an optional non-null string.
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"error": optionalNonNullTypeScriptSchema(Schema{"type": "string"}),
				"threadId": Schema{"anyOf": []any{
					Schema{"type": "string"}, Schema{"type": "null"},
				}},
			})
			schema, _ := typeScriptSchema(definition)
			required, _ := schema["required"].([]string)
			schema["required"] = append(append([]string(nil), required...), "threadId")
			definition = schema
		}
		if name == "McpServerOauthLoginParams" ||
			name == "McpServerOauthLoginResponse" ||
			name == "McpServerOauthLoginCompletedNotification" {
			schema, _ := typeScriptSchema(definition)
			schema["x-gollem-typescript-ignore-additional-properties"] = true
			definition = schema
		}
		if name == "ReviewTarget" {
			// ts-rs requires the nullable commit title even though serde accepts
			// its omission. Keep that render-only distinction out of JSON Schema.
			schema, _ := typeScriptSchema(definition)
			for _, rawVariant := range schema["oneOf"].([]any) {
				variant := rawVariant.(Schema)
				variant["x-gollem-typescript-ignore-additional-properties"] = true
				properties := variant["properties"].(Schema)
				tag := properties["type"].(Schema)["enum"].([]any)[0]
				if tag == "commit" {
					variant["required"] = []string{"sha", "title", "type"}
					properties["title"] = Schema{"anyOf": []any{
						Schema{"type": "string"}, Schema{"type": "null"},
					}}
				}
			}
			definition = schema
		}
		if name == "ReviewStartParams" || name == "ReviewStartResponse" {
			// The source schema permits forward-compatible fields, while ts-rs
			// renders these public records as closed object literals.
			schema, _ := typeScriptSchema(definition)
			schema["x-gollem-typescript-ignore-additional-properties"] = true
			definition = schema
		}
		if name == "ThreadExtra" {
			// The source schema intentionally leaves this extension record open,
			// while ts-rs renders its empty Rust struct as Record<string, never>.
			schema, _ := typeScriptSchema(definition)
			schema["additionalProperties"] = false
			definition = schema
		}
		if name == "ThreadInjectItemsParams" || name == "ThreadInjectItemsResponse" {
			// The source schemas remain open for forward compatibility, while
			// ts-rs closes both Rust structs. JsonValue is render-only because the
			// source JSON Schema represents serde_json::Value as items: true.
			schema, _ := typeScriptSchema(definition)
			schema["x-gollem-typescript-ignore-additional-properties"] = true
			if name == "ThreadInjectItemsParams" {
				schema = typeScriptDefinitionWithPropertySchemas(schema, Schema{
					"items": Schema{"type": "array", "items": Schema{"$ref": "#/$defs/JsonValue"}},
				})
			} else {
				schema["additionalProperties"] = false
			}
			definition = schema
		}
		if name == "ThreadRollbackParams" || name == "ThreadRollbackResponse" {
			// The source schemas remain open for forward compatibility, while
			// ts-rs renders their Rust structs as closed object literals. The
			// response wraps Thread in allOf only to attach documentation.
			schema, _ := typeScriptSchema(definition)
			schema["x-gollem-typescript-ignore-additional-properties"] = true
			if name == "ThreadRollbackResponse" {
				schema = typeScriptDefinitionWithPropertySchemas(schema, Schema{
					"thread": Schema{"$ref": "#/$defs/Thread"},
				})
			}
			definition = schema
		}
		if name == "ThreadSearchResult" {
			// The aggregate source schema permits forward-compatible fields, while
			// ts-rs renders the Rust struct as a closed object literal.
			schema, _ := typeScriptSchema(definition)
			schema["x-gollem-typescript-ignore-additional-properties"] = true
			definition = schema
		}
		if name == "ThreadShellCommandParams" || name == "ThreadShellCommandResponse" {
			// The source schemas remain open for forward compatibility, while
			// ts-rs renders both public Rust structs as closed object literals.
			schema, _ := typeScriptSchema(definition)
			schema["x-gollem-typescript-ignore-additional-properties"] = true
			if name == "ThreadShellCommandResponse" {
				schema["additionalProperties"] = false
			}
			definition = schema
		}
		if name == "ThreadApproveGuardianDeniedActionParams" || name == "ThreadApproveGuardianDeniedActionResponse" {
			// The source schemas remain open for serde compatibility, while ts-rs
			// renders the request as a closed JsonValue record and the empty
			// response as Record<string, never>.
			schema, _ := typeScriptSchema(definition)
			schema["x-gollem-typescript-ignore-additional-properties"] = true
			if name == "ThreadApproveGuardianDeniedActionParams" {
				schema = typeScriptDefinitionWithPropertySchemas(schema, Schema{
					"event": Schema{"$ref": "#/$defs/JsonValue"},
				})
			} else {
				schema["additionalProperties"] = false
			}
			definition = schema
		}
		if name == "W3cTraceContext" {
			// Rust accepts explicit null as None, but ts-rs renders its optional
			// fields as strings without a null union. Preserve that distinction in
			// the renderer only; the source JSON Schema remains nullable and open.
			schema, _ := typeScriptSchema(definition)
			schema["x-gollem-typescript-ignore-additional-properties"] = true
			definition = typeScriptDefinitionWithPropertySchemas(schema, Schema{
				"traceparent": Schema{"type": "string"},
				"tracestate":  Schema{"type": "string"},
			})
		}
		if name == "ClientNotification" {
			// The source schema remains open for serde-compatible unknown fields,
			// while ts-rs renders the one unit variant as a closed object literal.
			schema, _ := typeScriptSchema(definition)
			for _, rawVariant := range schema["oneOf"].([]any) {
				rawVariant.(Schema)["x-gollem-typescript-ignore-additional-properties"] = true
			}
			definition = schema
		}
		if name == "JSONRPCError" || name == "JSONRPCErrorError" ||
			name == "JSONRPCNotification" || name == "JSONRPCRequest" || name == "JSONRPCResponse" {
			// The source records are serde-open in JSON Schema but closed in ts-rs.
			// serde_json::Value fields are rendered as the shared JsonValue alias.
			schema, _ := typeScriptSchema(definition)
			schema["x-gollem-typescript-ignore-additional-properties"] = true
			replacements := Schema{}
			switch name {
			case "JSONRPCErrorError":
				replacements["data"] = Schema{"$ref": "#/$defs/JsonValue"}
			case "JSONRPCNotification":
				replacements["params"] = Schema{"$ref": "#/$defs/JsonValue"}
			case "JSONRPCRequest":
				replacements["params"] = Schema{"$ref": "#/$defs/JsonValue"}
				replacements["trace"] = Schema{"$ref": "#/$defs/W3cTraceContext"}
			case "JSONRPCResponse":
				replacements["result"] = Schema{"$ref": "#/$defs/JsonValue"}
			}
			if len(replacements) > 0 {
				definition = typeScriptDefinitionWithPropertySchemas(schema, replacements)
			} else {
				definition = schema
			}
		}
		if name == "ThreadSettings" || name == "ThreadSettingsUpdatedNotification" {
			// The source schema permits forward-compatible fields, while ts-rs
			// renders these public records as closed object literals.
			schema, _ := typeScriptSchema(definition)
			schema["x-gollem-typescript-ignore-additional-properties"] = true
			if name == "ThreadSettings" {
				// The source JSON Schema uses a type array here, which ts-rs
				// renders as a nullable string union.
				schema["properties"].(Schema)["serviceTier"] = nullableStringSchema()
			}
			definition = schema
		}
		if name == "TurnEnvironmentParams" {
			// The source schema permits forward-compatible fields, while ts-rs
			// renders the public Rust struct as a closed object literal. Its
			// nullable string-array type needs a renderer-only anyOf shape.
			schema, _ := typeScriptSchema(definition)
			schema["x-gollem-typescript-ignore-additional-properties"] = true
			schema = typeScriptDefinitionWithPropertySchemas(schema, Schema{
				"runtimeWorkspaceRoots": Schema{"anyOf": []any{
					Schema{"type": "array", "items": Schema{"$ref": "#/$defs/LegacyAppPathString"}},
					Schema{"type": "null"},
				}},
			})
			definition = schema
		}
		switch name {
		case "PermissionProfileListParams":
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"cursor": nullableStringSchema(),
				"cwd":    nullableStringSchema(),
				"limit": Schema{"anyOf": []any{
					Schema{"type": "integer"}, Schema{"type": "null"},
				}},
			})
		case "PermissionProfileSummary":
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"description": nullableStringSchema(),
			})
		case "PermissionProfileListResponse":
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"nextCursor": nullableStringSchema(),
			})
		}
		if name == "PermissionProfileSummary" || name == "PermissionProfileListResponse" {
			// serde accepts omitted Option fields and emits them as null, while
			// ts-rs exposes these two properties as required nullable values.
			schema, _ := typeScriptSchema(definition)
			required, _ := schema["required"].([]string)
			required = append([]string(nil), required...)
			if name == "PermissionProfileSummary" {
				required = append(required, "description")
			} else {
				required = append(required, "nextCursor")
			}
			schema["required"] = required
			definition = schema
		}
		if name == "PermissionProfileListParams" ||
			name == "PermissionProfileSummary" ||
			name == "PermissionProfileListResponse" {
			schema, _ := typeScriptSchema(definition)
			schema["x-gollem-typescript-ignore-additional-properties"] = true
			definition = schema
		}
		switch name {
		case "AppsInstalledParams":
			definition = Schema{typeScriptRawTypeKeyword: `{ threadId?: string | null, forceRefresh?: boolean, }`}
		case "AppsReadParams":
			definition = Schema{typeScriptRawTypeKeyword: `{ appIds: Array<string>, threadId?: string | null, includeTools?: boolean, }`}
		case "FeedbackUploadParams":
			definition = Schema{typeScriptRawTypeKeyword: `{ classification: string, reason?: string | null, threadId?: string | null, includeLogs?: boolean, extraLogFiles?: Array<string> | null, tags?: { [key in string]?: string } | null, }`}
		case "WindowsSandboxSetupStartParams":
			definition = Schema{typeScriptRawTypeKeyword: `{ mode: WindowsSandboxSetupMode, cwd?: AbsolutePathBuf | null, }`}
		case "SkillsListParams":
			definition = Schema{typeScriptRawTypeKeyword: `{
/**
 * When empty, defaults to the current session working directory.
 */
cwds?: Array<string>,
/**
 * When true, bypass the skills cache and re-scan skills from disk.
 */
forceReload?: boolean, }`}
		case "SkillsExtraRootsSetParams":
			definition = Schema{typeScriptRawTypeKeyword: `{ extraRoots: Array<AbsolutePathBuf>, }`}
		case "SkillsConfigWriteParams":
			definition = Schema{typeScriptRawTypeKeyword: `{
/**
 * Path-based selector.
 */
path?: AbsolutePathBuf | null,
/**
 * Name-based selector.
 */
name?: string | null, enabled: boolean, }`}
		case "ExternalAgentConfigImportHistoryRecordSuccessParams":
			definition = Schema{typeScriptRawTypeKeyword: `{ itemType: ExternalAgentConfigMigrationItemType, cwd: string | null, source: string | null, target: string | null,
/**
 * Original title for an imported session, when available.
 */
title?: string | null, }`}
		case "ExternalAgentConfigImportHistoryRecordTypeResultParams":
			definition = Schema{typeScriptRawTypeKeyword: `{ itemType: ExternalAgentConfigMigrationItemType, successes: Array<ExternalAgentConfigImportHistoryRecordSuccessParams>, failures: Array<ExternalAgentConfigImportItemTypeFailure>, }`}
		case "ExternalAgentConfigImportHistoryRecordParams":
			definition = Schema{typeScriptRawTypeKeyword: `{
/**
 * Opaque provider identifier for the externally completed import.
 */
providerId: string,
/**
 * Completed results grouped by imported item type.
 */
itemTypeResults: Array<ExternalAgentConfigImportHistoryRecordTypeResultParams>, }`}
		case "PluginShareCheckoutParams":
			definition = Schema{typeScriptRawTypeKeyword: `{ remotePluginId: string, }`}
		case "PluginShareTarget":
			definition = Schema{typeScriptRawTypeKeyword: `{ principalType: PluginSharePrincipalType, principalId: string, role: PluginShareTargetRole, }`}
		case "PluginShareSaveParams":
			definition = Schema{typeScriptRawTypeKeyword: `{ pluginPath: AbsolutePathBuf, remotePluginId?: string | null, discoverability?: PluginShareDiscoverability | null, shareTargets?: Array<PluginShareTarget> | null, }`}
		case "PluginShareUpdateTargetsParams":
			definition = Schema{typeScriptRawTypeKeyword: `{ remotePluginId: string, discoverability: PluginShareUpdateDiscoverability, shareTargets: Array<PluginShareTarget>, }`}
		case "PluginShareDeleteParams":
			definition = Schema{typeScriptRawTypeKeyword: `{ remotePluginId: string, }`}
		case "PluginReadParams":
			definition = Schema{typeScriptRawTypeKeyword: `{ marketplacePath?: AbsolutePathBuf | null, remoteMarketplaceName?: string | null, pluginName: string, }`}
		case "PluginInstallParams":
			definition = Schema{typeScriptRawTypeKeyword: `{ marketplacePath?: AbsolutePathBuf | null, remoteMarketplaceName?: string | null,
/**
 * Client-generated identifier used to correlate one installation attempt.
 */
installAttemptId?: string | null, pluginName: string, }`}
		case "PluginInstalledParams":
			definition = Schema{typeScriptRawTypeKeyword: `{
/**
 * Optional working directories used to discover repo marketplaces.
 */
cwds?: Array<AbsolutePathBuf> | null,
/**
 * Additional uninstalled plugin names that should be returned when present locally.
 * This is used by mention surfaces that intentionally expose install entrypoints.
 */
installSuggestionPluginNames?: Array<string> | null, }`}
		case "PluginListParams":
			definition = Schema{typeScriptRawTypeKeyword: `{
/**
 * Optional working directories used to discover repo marketplaces. When omitted,
 * only home-scoped marketplaces and the official curated marketplace are considered.
 */
cwds?: Array<AbsolutePathBuf> | null,
/**
 * Optional marketplace kind filter. When omitted, only local marketplaces are queried, plus
 * the default remote catalog when enabled by feature flag.
 */
marketplaceKinds?: Array<PluginListMarketplaceKind> | null,
/**
 * Whether the client requests a fresh remote plugin catalog fetch.
 */
forceRefetch?: boolean, }`}
		case "PluginShareListParams":
			definition = Schema{typeScriptRawTypeKeyword: `Record<string, never>`}
		case "PluginSkillReadParams":
			definition = Schema{typeScriptRawTypeKeyword: `{ remoteMarketplaceName: string, remotePluginId: string, skillName: string, }`}
		case "PluginUninstallParams":
			definition = Schema{typeScriptRawTypeKeyword: `{ pluginId: string, }`}
		case "MarketplaceAddParams":
			definition = Schema{typeScriptRawTypeKeyword: `{ source: string, refName?: string | null, sparsePaths?: Array<string> | null, }`}
		case "MarketplaceRemoveParams":
			definition = Schema{typeScriptRawTypeKeyword: `{ marketplaceName: string, }`}
		case "MarketplaceUpgradeParams":
			definition = Schema{typeScriptRawTypeKeyword: `{ marketplaceName?: string | null, }`}
		case "McpServerElicitationRequestParams":
			// The raw schema mirrors serde's open, flattened record. ts-rs instead
			// emits the exact closed intersection and makes Option fields nullable.
			definition = Schema{
				typeScriptRawTypeKeyword: `{ "threadId": string; "turnId": string | null; "serverName": string; } & ({ "mode": "form"; "_meta": JsonValue | null; "message": string; "requestedSchema": McpElicitationSchema; } | { "mode": "openai/form"; "_meta": JsonValue | null; "message": string; "requestedSchema": JsonValue; } | { "mode": "url"; "_meta": JsonValue | null; "message": string; "url": string; "elicitationId": string; })`,
			}
		case "McpServerElicitationRequestResponse":
			// serde accepts omitted optional values, but ts-rs exposes their
			// canonical nullable representation in the public TypeScript binding.
			definition = Schema{
				typeScriptRawTypeKeyword: `{ "action": McpServerElicitationAction; "content": JsonValue | null; "_meta": JsonValue | null; }`,
			}
		case "DynamicToolCallParams":
			definition = Schema{
				typeScriptRawTypeKeyword: `{ "threadId": string; "turnId": string; "callId": string; "namespace": string | null; "tool": string; "arguments": JsonValue; }`,
			}
		case "DynamicToolCallResponse":
			definition = Schema{
				typeScriptRawTypeKeyword: `{ "contentItems": Array<DynamicToolCallOutputContentItem>; "success": boolean; }`,
			}
		case "DynamicToolCallOutputContentItem":
			definition = Schema{
				typeScriptRawTypeKeyword: `{ "type": "inputText"; "text": string; } | { "type": "inputImage"; "imageUrl": string; } | { "type": "inputAudio"; "audioUrl": string; }`,
			}
		case "ServerRequest":
			definition = Schema{
				typeScriptRawTypeKeyword: `{ "method": "item/commandExecution/requestApproval"; "id": RequestId; "params": CommandExecutionRequestApprovalParams; } | { "method": "item/fileChange/requestApproval"; "id": RequestId; "params": FileChangeRequestApprovalParams; } | { "method": "item/tool/requestUserInput"; "id": RequestId; "params": ToolRequestUserInputParams; } | { "method": "mcpServer/elicitation/request"; "id": RequestId; "params": McpServerElicitationRequestParams; } | { "method": "item/permissions/requestApproval"; "id": RequestId; "params": PermissionsRequestApprovalParams; } | { "method": "item/tool/call"; "id": RequestId; "params": DynamicToolCallParams; } | { "method": "account/chatgptAuthTokens/refresh"; "id": RequestId; "params": ChatgptAuthTokensRefreshParams; } | { "method": "attestation/generate"; "id": RequestId; "params": AttestationGenerateParams; } | { "method": "currentTime/read"; "id": RequestId; "params": CurrentTimeReadParams; } | { "method": "applyPatchApproval"; "id": RequestId; "params": ApplyPatchApprovalParams; } | { "method": "execCommandApproval"; "id": RequestId; "params": ExecCommandApprovalParams; }`,
			}
		case "ThreadSectionAppearance":
			definition = Schema{typeScriptRawTypeKeyword: `{ icon: string | null, color: string | null, }`}
		case "ThreadSectionCreateParams":
			definition = Schema{typeScriptRawTypeKeyword: `{ name: string, appearance?: ThreadSectionAppearance | null, }`}
		case "ThreadSectionDeleteParams":
			definition = Schema{typeScriptRawTypeKeyword: `{ sectionId: string, }`}
		case "ThreadSectionListParams":
			definition = Schema{typeScriptRawTypeKeyword: `{ cursor?: string | null, limit?: number | null, }`}
		case "ThreadSectionMoveParams":
			definition = Schema{typeScriptRawTypeKeyword: `{ threadId: string, sectionId: string | null, beforeThreadId?: string | null, }`}
		case "ThreadSectionUpdateParams":
			definition = Schema{typeScriptRawTypeKeyword: `{ sectionId: string, name: string, appearance?: ThreadSectionAppearance | null, }`}
		case "DynamicToolFunctionSpec", "DynamicToolNamespaceSpec":
			schema, _ := typeScriptSchema(definition)
			schema["x-gollem-typescript-ignore-additional-properties"] = true
			definition = schema
		case "DynamicToolNamespaceTool":
			definition = Schema{
				typeScriptRawTypeKeyword: `{ "type": "function" } & DynamicToolFunctionSpec`,
			}
		case "DynamicToolSpec":
			definition = Schema{
				typeScriptRawTypeKeyword: `{ "type": "function" } & DynamicToolFunctionSpec | { "type": "namespace" } & DynamicToolNamespaceSpec`,
			}
		}
		switch name {
		case "CapabilityRootLocation":
			definition = Schema{
				typeScriptRawTypeKeyword: `{ "type": "environment"; "environmentId": string; "path": string; }`,
			}
		case "CollaborationMode":
			definition = Schema{
				typeScriptRawTypeKeyword: `{ "mode": ModeKind; "settings": Settings; }`,
			}
		case "CollaborationModeMask":
			definition = Schema{
				typeScriptRawTypeKeyword: `{ "name": string; "mode": ModeKind | null; "model": string | null; "reasoning_effort": ReasoningEffort | null | null; }`,
			}
		case "ModeKind":
			definition = Schema{typeScriptRawTypeKeyword: `"plan" | "default"`}
		case "MultiAgentMode":
			definition = Schema{
				typeScriptRawTypeKeyword: `{ "custom": string } | "explicitRequestOnly" | "proactive"`,
			}
		case "SelectedCapabilityRoot":
			definition = Schema{
				typeScriptRawTypeKeyword: `{ "id": string; "location": CapabilityRootLocation; }`,
			}
		case "Settings":
			definition = Schema{
				typeScriptRawTypeKeyword: `{ "model": string; "reasoning_effort": ReasoningEffort | null; "developer_instructions": string | null; }`,
			}
		}
		if name == "HookRunSummary" {
			// ts-rs maps each Rust i64 field to bigint, including nullable i64
			// options. Keep these hints out of the public JSON Schema.
			definition = typeScriptDefinitionWithBigIntProperties(
				definition, "displayOrder", "startedAt", "completedAt", "durationMs",
			)
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"source":        Schema{"$ref": "#/$defs/HookSource"},
				"statusMessage": Schema{"anyOf": []any{Schema{"type": "string"}, Schema{"type": "null"}}},
			})
		}
		if name == "HookMetadata" {
			// ts-rs maps Rust u64 and i64 fields to bigint. Keep the render hints
			// out of the exact public JSON Schema.
			definition = typeScriptDefinitionWithBigIntProperties(
				definition, "timeoutSec", "displayOrder",
			)
			nullableString := Schema{
				"anyOf": []any{Schema{"type": "string"}, Schema{"type": "null"}},
			}
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"matcher": nullableString, "command": nullableString,
				"statusMessage": nullableString, "pluginId": nullableString,
			})
		}
		if name == "HookStartedNotification" || name == "HookCompletedNotification" {
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"turnId": Schema{"anyOf": []any{Schema{"type": "string"}, Schema{"type": "null"}}},
			})
		}
		if name == "GuardianApprovalReview" {
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"rationale": Schema{"anyOf": []any{Schema{"type": "string"}, Schema{"type": "null"}}},
			})
		}
		if name == "GuardianApprovalReviewAction" {
			definition = guardianApprovalReviewActionTypeScriptSchema(definition)
		}
		if name == "FileChange" {
			definition = fileChangeTypeScriptSchema(definition)
		}
		if name == "ItemGuardianApprovalReviewCompletedNotification" ||
			name == "ItemGuardianApprovalReviewStartedNotification" {
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"targetItemId": Schema{
					"anyOf": []any{Schema{"type": "string"}, Schema{"type": "null"}},
				},
			})
		}
		typeName, err := typeScriptType(definition, 0)
		if err != nil {
			return nil, fmt.Errorf("generate TypeScript definition %s: %w", name, err)
		}
		fmt.Fprintf(&out, "export type %s = %s;\n\n", name, typeName)
	}

	writeTypeScriptWireBindings(&out)
	writeTypeScriptItemBindings(&out)
	return out.Bytes(), nil
}

func mcpServerStatusTypeScriptDefinition(name string, definition any) Schema {
	schema, _ := typeScriptSchema(definition)
	replacements := Schema{}
	switch name {
	case "Resource":
		replacements = Schema{
			"description": optionalNonNullTypeScriptSchema(Schema{"type": "string"}),
			"icons": optionalNonNullTypeScriptSchema(Schema{
				"type": "array", "items": Schema{"$ref": "#/$defs/JsonValue"},
			}),
			"mimeType": optionalNonNullTypeScriptSchema(Schema{"type": "string"}),
			"size": optionalNonNullTypeScriptSchema(Schema{
				"type": "integer", "format": "int64",
			}),
			"title": optionalNonNullTypeScriptSchema(Schema{"type": "string"}),
		}
	case "ResourceTemplate":
		replacements = Schema{
			"description": optionalNonNullTypeScriptSchema(Schema{"type": "string"}),
			"mimeType":    optionalNonNullTypeScriptSchema(Schema{"type": "string"}),
			"title":       optionalNonNullTypeScriptSchema(Schema{"type": "string"}),
		}
	case "Tool":
		replacements = Schema{
			"description": optionalNonNullTypeScriptSchema(Schema{"type": "string"}),
			"icons": optionalNonNullTypeScriptSchema(Schema{
				"type": "array", "items": Schema{"$ref": "#/$defs/JsonValue"},
			}),
			"title": optionalNonNullTypeScriptSchema(Schema{"type": "string"}),
		}
	case "McpServerStatus":
		replacements = Schema{
			"tools": Schema{
				"type": "object", "additionalProperties": Schema{"$ref": "#/$defs/Tool"},
				"x-gollem-typescript-optional-map": true,
			},
		}
	case "ListMcpServerStatusResponse":
		replacements = Schema{"nextCursor": nullableStringSchema()}
	}
	renderSchema := typeScriptDefinitionWithPropertySchemas(schema, replacements)
	renderSchema["x-gollem-typescript-ignore-additional-properties"] = true
	if name == "McpServerStatus" {
		renderSchema["required"] = []string{
			"authStatus", "name", "resourceTemplates", "resources", "serverInfo", "tools",
		}
	}
	if name == "ListMcpServerStatusResponse" {
		renderSchema["required"] = []string{"data", "nextCursor"}
	}
	return renderSchema
}

func optionalNonNullTypeScriptSchema(value Schema) Schema {
	return Schema{
		"anyOf":                          []any{value, Schema{"type": "null"}},
		typeScriptOptionalNonNullKeyword: true,
	}
}

func writeTypeScriptProtocolMetadata(out *bytes.Buffer) {
	out.WriteString("export type ProtocolSurface =\n")
	for i, surface := range []Surface{
		SurfaceClientRequest,
		SurfaceServerNotification,
		SurfaceServerRequest,
		SurfaceClientNotification,
		SurfaceGollemExtension,
	} {
		terminator := "\n"
		if i == 4 {
			terminator = ";\n\n"
		}
		fmt.Fprintf(out, "  | %s%s", typeScriptString(string(surface)), terminator)
	}
	out.WriteString("export type ProtocolMethodState =\n")
	states := []MethodState{
		MethodImplemented,
		MethodBlocked,
		MethodDeferredStub,
		MethodRenamedEquivalent,
		MethodNotApplicable,
	}
	for i, state := range states {
		terminator := "\n"
		if i == len(states)-1 {
			terminator = ";\n\n"
		}
		fmt.Fprintf(out, "  | %s%s", typeScriptString(string(state)), terminator)
	}
	out.WriteString("export type ProtocolMethodInfo = {\n")
	out.WriteString("  \"method\": string;\n")
	out.WriteString("  \"surface\": ProtocolSurface;\n")
	out.WriteString("  \"state\": ProtocolMethodState;\n")
	out.WriteString("  \"source\"?: string;\n")
	out.WriteString("};\n\n")

	methods := Methods()
	out.WriteString("export const protocolMethods = [\n")
	for _, method := range methods {
		fmt.Fprintf(out, "  { \"method\": %s, \"surface\": %s, \"state\": %s", typeScriptString(method.Method), typeScriptString(string(method.Surface)), typeScriptString(string(method.State)))
		if method.Source != "" {
			fmt.Fprintf(out, ", \"source\": %s", typeScriptString(method.Source))
		}
		out.WriteString(" },\n")
	}
	out.WriteString("] as const satisfies readonly ProtocolMethodInfo[];\n\n")

	writeTypeScriptMethodUnion(out, "ClientRequestMethod", MethodsBySurface(SurfaceClientRequest))
	writeTypeScriptMethodUnion(out, "ServerNotificationMethod", MethodsBySurface(SurfaceServerNotification))
	writeTypeScriptMethodUnion(out, "ServerRequestMethod", MethodsBySurface(SurfaceServerRequest))
	writeTypeScriptMethodUnion(out, "ClientNotificationMethod", MethodsBySurface(SurfaceClientNotification))
	writeTypeScriptMethodUnion(out, "GollemExtensionMethod", MethodsBySurface(SurfaceGollemExtension))
	out.WriteString("export type KnownMethod =\n")
	out.WriteString("  | ClientRequestMethod\n")
	out.WriteString("  | ServerNotificationMethod\n")
	out.WriteString("  | ServerRequestMethod\n")
	out.WriteString("  | ClientNotificationMethod\n")
	out.WriteString("  | GollemExtensionMethod;\n\n")
}

func writeTypeScriptMethodUnion(out *bytes.Buffer, name string, methods []MethodInfo) {
	fmt.Fprintf(out, "export type %s =", name)
	if len(methods) == 0 {
		out.WriteString(" never;\n\n")
		return
	}
	out.WriteByte('\n')
	for i, method := range methods {
		terminator := "\n"
		if i == len(methods)-1 {
			terminator = ";\n\n"
		}
		fmt.Fprintf(out, "  | %s%s", typeScriptString(method.Method), terminator)
	}
}

func writeTypeScriptWireBindings(out *bytes.Buffer) {
	bindings := WireTypeBindings()
	out.WriteString("export type WireTypeBinding = {\n")
	out.WriteString("  \"method\": KnownMethod;\n")
	out.WriteString("  \"surface\": ProtocolSurface;\n")
	out.WriteString("  \"params\"?: readonly string[];\n")
	out.WriteString("  \"result\"?: readonly string[];\n")
	out.WriteString("};\n\n")
	out.WriteString("export const wireTypeBindings = [\n")
	for _, binding := range bindings {
		fmt.Fprintf(out, "  { \"method\": %s, \"surface\": %s", typeScriptString(binding.Method), typeScriptString(string(binding.Surface)))
		if len(binding.Params) > 0 {
			fmt.Fprintf(out, ", \"params\": %s", typeScriptStringArray(binding.Params))
		}
		if len(binding.Result) > 0 {
			fmt.Fprintf(out, ", \"result\": %s", typeScriptStringArray(binding.Result))
		}
		out.WriteString(" },\n")
	}
	out.WriteString("] as const satisfies readonly WireTypeBinding[];\n\n")

	out.WriteString("export interface MethodParamsByName {\n")
	for _, binding := range bindings {
		fmt.Fprintf(out, "  %s: %s;\n", typeScriptString(binding.Method), typeScriptTypeUnion(binding.Params, "undefined"))
	}
	out.WriteString("}\n\n")
	out.WriteString("export interface MethodResultsByName {\n")
	for _, binding := range bindings {
		if len(binding.Result) == 0 {
			continue
		}
		fmt.Fprintf(out, "  %s: %s;\n", typeScriptString(binding.Method), typeScriptTypeUnion(binding.Result, "never"))
	}
	out.WriteString("}\n\n")
	out.WriteString("export type BoundRequestMethod = Extract<\n")
	out.WriteString("  keyof MethodParamsByName,\n")
	out.WriteString("  ClientRequestMethod | ServerRequestMethod | GollemExtensionMethod\n")
	out.WriteString(">;\n")
	out.WriteString("export type BoundNotificationMethod = Extract<\n")
	out.WriteString("  keyof MethodParamsByName,\n")
	out.WriteString("  ServerNotificationMethod | ClientNotificationMethod\n")
	out.WriteString(">;\n\n")
	out.WriteString("export type ParamsFor<M extends keyof MethodParamsByName> = MethodParamsByName[M];\n")
	out.WriteString("export type ResultFor<M extends keyof MethodResultsByName> = MethodResultsByName[M];\n\n")
	out.WriteString("export type BoundRequest<M extends BoundRequestMethod> =\n")
	out.WriteString("  MethodParamsByName[M] extends undefined\n")
	out.WriteString("    ? { \"id\": RequestID; \"method\": M; \"params\"?: never }\n")
	out.WriteString("    : { \"id\": RequestID; \"method\": M; \"params\": MethodParamsByName[M] };\n\n")
	out.WriteString("export type BoundNotification<M extends BoundNotificationMethod> =\n")
	out.WriteString("  MethodParamsByName[M] extends undefined\n")
	out.WriteString("    ? { \"method\": M; \"params\"?: never }\n")
	out.WriteString("    : { \"method\": M; \"params\": MethodParamsByName[M] };\n\n")
	out.WriteString("export type BoundResponse<M extends keyof MethodResultsByName> =\n")
	out.WriteString("  | { \"id\": RequestID; \"result\": MethodResultsByName[M]; \"error\"?: never }\n")
	out.WriteString("  | { \"id\": RequestID; \"result\"?: never; \"error\": Error };\n\n")
}

func writeTypeScriptItemBindings(out *bytes.Buffer) {
	bindings := ItemPayloadBindings()
	out.WriteString("export type ItemPayloadBinding = {\n")
	out.WriteString("  \"kind\": string;\n")
	out.WriteString("  \"type\": string;\n")
	out.WriteString("};\n\n")
	out.WriteString("export const itemPayloadBindings = [\n")
	for _, binding := range bindings {
		fmt.Fprintf(out, "  { \"kind\": %s, \"type\": %s },\n", typeScriptString(binding.Kind), typeScriptString(binding.Type))
	}
	out.WriteString("] as const satisfies readonly ItemPayloadBinding[];\n\n")
	out.WriteString("export interface ItemPayloadByKind {\n")
	for _, binding := range bindings {
		fmt.Fprintf(out, "  %s: %s;\n", typeScriptString(binding.Kind), binding.Type)
	}
	out.WriteString("}\n\n")
	out.WriteString("export type KnownItemKind = keyof ItemPayloadByKind;\n")
	out.WriteString("export type KnownItemPayload = ItemPayloadByKind[KnownItemKind];\n")
	out.WriteString("export type KnownTimelineItem = {\n")
	out.WriteString("  [K in KnownItemKind]: Omit<TimelineItem, \"kind\" | \"payload\"> & {\n")
	out.WriteString("    \"kind\": K;\n")
	out.WriteString("    \"payload\": ItemPayloadByKind[K];\n")
	out.WriteString("  };\n")
	out.WriteString("}[KnownItemKind];\n")
}

func typeScriptDefinitionWithBigIntProperties(definition any, names ...string) Schema {
	schema, _ := typeScriptSchema(definition)
	renderSchema := make(Schema, len(schema))
	for key, value := range schema {
		renderSchema[key] = value
	}
	properties, _ := typeScriptSchema(schema["properties"])
	renderProperties := make(Schema, len(properties))
	for key, value := range properties {
		renderProperties[key] = value
	}
	for _, name := range names {
		property, _ := typeScriptSchema(properties[name])
		renderProperty := make(Schema, len(property)+1)
		for key, value := range property {
			renderProperty[key] = value
		}
		renderProperty[typeScriptBigIntKeyword] = true
		renderProperties[name] = renderProperty
	}
	renderSchema["properties"] = renderProperties
	return renderSchema
}

func typeScriptDefinitionWithPropertySchemas(definition any, replacements Schema) Schema {
	schema, _ := typeScriptSchema(definition)
	renderSchema := make(Schema, len(schema))
	for key, value := range schema {
		renderSchema[key] = value
	}
	properties, _ := typeScriptSchema(schema["properties"])
	renderProperties := make(Schema, len(properties))
	for key, value := range properties {
		renderProperties[key] = value
	}
	for name, replacement := range replacements {
		renderProperties[name] = replacement
	}
	renderSchema["properties"] = renderProperties
	return renderSchema
}

func guardianApprovalReviewActionTypeScriptSchema(definition any) Schema {
	schema, _ := typeScriptSchema(definition)
	renderSchema := make(Schema, len(schema))
	for key, value := range schema {
		renderSchema[key] = value
	}
	variants, _ := typeScriptAnySlice(schema["oneOf"])
	renderVariants := make([]any, 0, len(variants))
	for _, rawVariant := range variants {
		variant, _ := typeScriptSchema(rawVariant)
		renderVariant := make(Schema, len(variant))
		for key, value := range variant {
			renderVariant[key] = value
		}
		properties, _ := typeScriptSchema(variant["properties"])
		renderProperties := make(Schema, len(properties))
		for key, value := range properties {
			renderProperties[key] = value
		}
		typeSchema, _ := typeScriptSchema(properties["type"])
		tags, _ := typeScriptAnySlice(typeSchema["enum"])
		required := append([]string(nil), variant["required"].([]string)...)
		var nullableFields []string
		if len(tags) == 1 {
			switch tags[0] {
			case "mcpToolCall":
				nullableFields = []string{"connectorId", "connectorName", "toolTitle"}
			case "requestPermissions":
				nullableFields = []string{"reason"}
			}
		}
		for _, field := range nullableFields {
			required = append(required, field)
			renderProperties[field] = Schema{"anyOf": []any{
				Schema{"type": "string"}, Schema{"type": "null"},
			}}
		}
		renderVariant["properties"] = renderProperties
		renderVariant["required"] = required
		renderVariants = append(renderVariants, renderVariant)
	}
	renderSchema["oneOf"] = renderVariants
	return renderSchema
}

func fileChangeTypeScriptSchema(definition any) Schema {
	schema, _ := typeScriptSchema(definition)
	renderSchema := make(Schema, len(schema))
	for key, value := range schema {
		renderSchema[key] = value
	}
	variants, _ := typeScriptAnySlice(schema["oneOf"])
	renderVariants := make([]any, 0, len(variants))
	for _, rawVariant := range variants {
		variant, _ := typeScriptSchema(rawVariant)
		renderVariant := make(Schema, len(variant))
		for key, value := range variant {
			renderVariant[key] = value
		}
		properties, _ := typeScriptSchema(variant["properties"])
		typeSchema, _ := typeScriptSchema(properties["type"])
		tags, _ := typeScriptAnySlice(typeSchema["enum"])
		if len(tags) == 1 && tags[0] == "update" {
			renderProperties := make(Schema, len(properties))
			for key, value := range properties {
				renderProperties[key] = value
			}
			renderProperties["move_path"] = Schema{"anyOf": []any{
				Schema{"type": "string"}, Schema{"type": "null"},
			}}
			required := append([]string(nil), variant["required"].([]string)...)
			required = append(required, "move_path")
			renderVariant["properties"] = renderProperties
			renderVariant["required"] = required
		}
		renderVariants = append(renderVariants, renderVariant)
	}
	renderSchema["oneOf"] = renderVariants
	return renderSchema
}

func typeScriptType(value any, indent int) (string, error) {
	schema, ok := typeScriptSchema(value)
	if !ok || len(schema) == 0 {
		return "unknown", nil
	}
	if rawType, ok := schema[typeScriptRawTypeKeyword].(string); ok {
		if rawType == "" {
			return "", errors.New("TypeScript raw type must not be empty")
		}
		return rawType, nil
	}
	if bigint, _ := schema[typeScriptBigIntKeyword].(bool); bigint {
		if schema["type"] == "integer" {
			return "bigint", nil
		}
		types, ok := typeScriptAnySlice(schema["type"])
		if !ok {
			return "", errors.New("TypeScript bigint schema must have integer type")
		}
		parts := make([]string, 0, len(types))
		for _, value := range types {
			switch value {
			case "integer":
				parts = appendUniqueTypeScript(parts, "bigint")
			case "null":
				parts = appendUniqueTypeScript(parts, "null")
			default:
				return "", errors.New("TypeScript bigint schema type array must contain only integer and null")
			}
		}
		if !slices.Contains(parts, "bigint") {
			return "", errors.New("TypeScript bigint schema type array must contain integer")
		}
		return strings.Join(parts, " | "), nil
	}
	if ref, ok := schema["$ref"].(string); ok {
		const prefix = "#/$defs/"
		if !strings.HasPrefix(ref, prefix) || len(ref) == len(prefix) {
			return "", fmt.Errorf("unsupported ref %q", ref)
		}
		return strings.TrimPrefix(ref, prefix), nil
	}
	if values, ok := typeScriptAnySlice(schema["enum"]); ok {
		return typeScriptLiteralUnion(values), nil
	}
	for _, keyword := range []string{"oneOf", "anyOf"} {
		if variants, ok := typeScriptAnySlice(schema[keyword]); ok {
			parts := make([]string, 0, len(variants))
			for _, variant := range variants {
				part, err := typeScriptType(variant, indent)
				if err != nil {
					return "", err
				}
				parts = appendUniqueTypeScript(parts, part)
			}
			if len(parts) == 0 {
				return "never", nil
			}
			return strings.Join(parts, " | "), nil
		}
	}

	typeName, _ := schema["type"].(string)
	switch typeName {
	case "string":
		return "string", nil
	case "integer", "number":
		return "number", nil
	case "boolean":
		return "boolean", nil
	case "null":
		return "null", nil
	case "array":
		item, err := typeScriptType(schema["items"], indent)
		if err != nil {
			return "", err
		}
		return "Array<" + item + ">", nil
	case "object":
		return typeScriptObjectType(schema, indent)
	case "":
		return "unknown", nil
	default:
		return "", fmt.Errorf("unsupported schema type %q", typeName)
	}
}

func typeScriptObjectType(schema Schema, indent int) (string, error) {
	properties, _ := typeScriptSchema(schema["properties"])
	required := typeScriptRequiredNames(schema["required"])
	additional, additionalIsSchema := typeScriptSchema(schema["additionalProperties"])
	additionalAllowed := true
	if allowed, ok := schema["additionalProperties"].(bool); ok {
		additionalAllowed = allowed
	}
	if len(properties) == 0 {
		if additionalIsSchema {
			valueType, err := typeScriptType(additional, indent)
			if err != nil {
				return "", err
			}
			if recursive, _ := schema["x-gollem-typescript-recursive-map"].(bool); recursive {
				return "{ [key: string]: " + valueType + " }", nil
			}
			if optional, _ := schema["x-gollem-typescript-optional-map"].(bool); optional {
				return "{ [key in string]?: " + valueType + " }", nil
			}
			return "Record<string, " + valueType + ">", nil
		}
		if !additionalAllowed {
			return "Record<string, never>", nil
		}
		return "Record<string, unknown>", nil
	}

	names := make([]string, 0, len(properties))
	for name := range properties {
		names = append(names, name)
	}
	sort.Strings(names)
	baseIndent := strings.Repeat("  ", indent)
	fieldIndent := strings.Repeat("  ", indent+1)
	var out strings.Builder
	out.WriteString("{\n")
	for _, name := range names {
		fieldValue := properties[name]
		fieldSchema, _ := typeScriptSchema(fieldValue)
		var fieldType string
		var err error
		if optionalNonNull, _ := fieldSchema[typeScriptOptionalNonNullKeyword].(bool); optionalNonNull {
			fieldType, err = typeScriptOptionalNonNullType(fieldSchema, indent+1)
		} else {
			fieldType, err = typeScriptType(fieldValue, indent+1)
		}
		if err != nil {
			return "", fmt.Errorf("property %s: %w", name, err)
		}
		optional := "?"
		if required[name] {
			optional = ""
		}
		fmt.Fprintf(&out, "%s%s%s: %s;\n", fieldIndent, typeScriptString(name), optional, fieldType)
	}
	out.WriteString(baseIndent)
	out.WriteByte('}')
	objectType := out.String()
	if additionalIsSchema {
		valueType, err := typeScriptType(additional, indent)
		if err != nil {
			return "", err
		}
		additionalType := "Record<string, " + valueType + ">"
		if optional, _ := schema["x-gollem-typescript-optional-map"].(bool); optional {
			additionalType = "{ [key in string]?: " + valueType + " }"
		}
		return "(" + objectType + " & " + additionalType + ")", nil
	}
	ignoreAdditional, _ := schema["x-gollem-typescript-ignore-additional-properties"].(bool)
	if additionalAllowed && !ignoreAdditional {
		return "(" + objectType + " & Record<string, unknown>)", nil
	}
	return objectType, nil
}

func typeScriptOptionalNonNullType(schema Schema, indent int) (string, error) {
	variants, ok := typeScriptAnySlice(schema["anyOf"])
	if !ok {
		return "", errors.New("optional non-null TypeScript schema requires anyOf")
	}
	nonNull := make([]any, 0, len(variants))
	for _, variant := range variants {
		variantSchema, _ := typeScriptSchema(variant)
		if variantSchema["type"] == "null" {
			continue
		}
		nonNull = append(nonNull, variant)
	}
	if len(nonNull) == 0 {
		return "", errors.New("optional non-null TypeScript schema has no non-null variant")
	}
	if len(nonNull) == 1 {
		return typeScriptType(nonNull[0], indent)
	}
	return typeScriptType(Schema{"anyOf": nonNull}, indent)
}

func typeScriptSchema(value any) (Schema, bool) {
	switch typed := value.(type) {
	case Schema:
		return typed, true
	case map[string]any:
		return Schema(typed), true
	default:
		return nil, false
	}
}

func typeScriptAnySlice(value any) ([]any, bool) {
	typed, ok := value.([]any)
	return typed, ok
}

func typeScriptRequiredNames(value any) map[string]bool {
	out := make(map[string]bool)
	switch typed := value.(type) {
	case []string:
		for _, name := range typed {
			out[name] = true
		}
	case []any:
		for _, item := range typed {
			if name, ok := item.(string); ok {
				out[name] = true
			}
		}
	}
	return out
}

func typeScriptLiteralUnion(values []any) string {
	parts := make([]string, 0, len(values))
	for _, value := range values {
		encoded, err := json.Marshal(value)
		if err != nil {
			parts = append(parts, "unknown")
			continue
		}
		parts = appendUniqueTypeScript(parts, string(encoded))
	}
	if len(parts) == 0 {
		return "never"
	}
	return strings.Join(parts, " | ")
}

func appendUniqueTypeScript(values []string, value string) []string {
	for _, existing := range values {
		if existing == value {
			return values
		}
	}
	return append(values, value)
}

func typeScriptTypeUnion(names []string, empty string) string {
	if len(names) == 0 {
		return empty
	}
	return strings.Join(names, " | ")
}

func typeScriptString(value string) string {
	encoded, _ := json.Marshal(value)
	return string(encoded)
}

func typeScriptStringArray(values []string) string {
	encoded := make([]string, 0, len(values))
	for _, value := range values {
		encoded = append(encoded, typeScriptString(value))
	}
	return "[" + strings.Join(encoded, ", ") + "]"
}

type typeScriptFixtureDocument struct {
	ProtocolVersion string                  `json:"protocolVersion"`
	SchemaVersion   string                  `json:"schemaVersion"`
	Cases           []typeScriptFixtureCase `json:"cases"`
}

type typeScriptFixtureCase struct {
	Name        string          `json:"name"`
	Surface     Surface         `json:"surface"`
	Method      string          `json:"method"`
	Envelope    string          `json:"envelope,omitempty"`
	ParamsType  string          `json:"paramsType,omitempty"`
	ResultType  string          `json:"resultType,omitempty"`
	PayloadType string          `json:"payloadType,omitempty"`
	Message     json.RawMessage `json:"message"`
}

type permissionProfileTypeScriptFixtureDocument struct {
	ProtocolVersion string          `json:"protocolVersion"`
	SchemaVersion   string          `json:"schemaVersion"`
	Request         json.RawMessage `json:"request"`
	Response        json.RawMessage `json:"response"`
}

// MarshalPermissionProfileTypeScriptFixture generates a strict compile fixture
// for the exported public permission types without creating a live binding.
func MarshalPermissionProfileTypeScriptFixture(data []byte) ([]byte, error) {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	var fixture permissionProfileTypeScriptFixtureDocument
	if err := decoder.Decode(&fixture); err != nil {
		return nil, fmt.Errorf("decode permission profile fixture: %w", err)
	}
	if err := decoder.Decode(&struct{}{}); !errors.Is(err, io.EOF) {
		if err == nil {
			return nil, errors.New("permission profile fixture must contain one JSON value")
		}
		return nil, err
	}
	if fixture.ProtocolVersion != ProtocolVersion || fixture.SchemaVersion != SchemaVersion {
		return nil, fmt.Errorf("fixture versions %s/%s do not match %s/%s", fixture.ProtocolVersion, fixture.SchemaVersion, ProtocolVersion, SchemaVersion)
	}
	var request, response bytes.Buffer
	if err := json.Indent(&request, fixture.Request, "", "  "); err != nil {
		return nil, fmt.Errorf("format permission request: %w", err)
	}
	if err := json.Indent(&response, fixture.Response, "", "  "); err != nil {
		return nil, fmt.Errorf("format permission response: %w", err)
	}

	var out bytes.Buffer
	out.WriteString(typeScriptGeneratedHeader)
	out.WriteString("import type {\n")
	for _, name := range []string{
		"ActivePermissionProfile",
		"AdditionalPermissionProfile",
		"FileSystemAccessMode",
		"FileSystemPath",
		"MethodResultsByName",
		"PermissionGrantScope",
		"PermissionsRequestApprovalParams",
		"PermissionsRequestApprovalResponse",
	} {
		fmt.Fprintf(&out, "  %s,\n", name)
	}
	out.WriteString("} from \"../gollem_appserver_protocol\";\n\n")
	fmt.Fprintf(&out, "export const fixtureProtocolVersion = %s as const;\n", typeScriptString(fixture.ProtocolVersion))
	fmt.Fprintf(&out, "export const fixtureSchemaVersion = %s as const;\n\n", typeScriptString(fixture.SchemaVersion))
	fmt.Fprintf(&out, "export const permissionProfileRequest = %s satisfies PermissionsRequestApprovalParams;\n\n", request.String())
	fmt.Fprintf(&out, "export const permissionProfileResponse = %s satisfies PermissionsRequestApprovalResponse;\n\n", response.String())
	out.WriteString("export const activePermissionProfile = { id: \":workspace\", extends: null } satisfies ActivePermissionProfile;\n")
	out.WriteString("export const additionalPermissionProfile = { network: null, fileSystem: null } satisfies AdditionalPermissionProfile;\n\n")
	out.WriteString("// @ts-expect-error filesystem access modes are closed.\n")
	out.WriteString("export const rejectInvalidFilesystemAccess = \"execute\" satisfies FileSystemAccessMode;\n")
	out.WriteString("// @ts-expect-error filesystem path variants cannot cross fields.\n")
	out.WriteString("export const rejectCrossedFilesystemPath = { type: \"path\", pattern: \"*.go\" } satisfies FileSystemPath;\n")
	out.WriteString("// @ts-expect-error permission grant scopes are closed.\n")
	out.WriteString("export const rejectInvalidPermissionScope = \"workspace\" satisfies PermissionGrantScope;\n")
	out.WriteString("// @ts-expect-error canonical permission requests require nullable environmentId.\n")
	out.WriteString("export const rejectMissingPermissionEnvironment = { threadId: \"t\", turnId: \"u\", itemId: \"i\", startedAtMs: 1, cwd: \"/workspace\", reason: null, permissions: { network: null, fileSystem: null } } satisfies PermissionsRequestApprovalParams;\n")
	out.WriteString("// @ts-expect-error canonical permission responses require scope.\n")
	out.WriteString("export const rejectMissingPermissionScope = { permissions: {} } satisfies PermissionsRequestApprovalResponse;\n")
	out.WriteString("// @ts-expect-error the incompatible live permission result remains unbound.\n")
	out.WriteString("export type RejectPermissionResultBinding = MethodResultsByName[\"item/permissions/requestApproval\"];\n")
	return out.Bytes(), nil
}

// MarshalTypeScriptFixture converts the versioned JSON wire examples into a
// TypeScript compile fixture using the generated method and payload bindings.
func MarshalTypeScriptFixture(data []byte) ([]byte, error) {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	var fixture typeScriptFixtureDocument
	if err := decoder.Decode(&fixture); err != nil {
		return nil, fmt.Errorf("decode runtime wire fixture: %w", err)
	}
	if fixture.ProtocolVersion != ProtocolVersion || fixture.SchemaVersion != SchemaVersion {
		return nil, fmt.Errorf("fixture versions %s/%s do not match %s/%s", fixture.ProtocolVersion, fixture.SchemaVersion, ProtocolVersion, SchemaVersion)
	}

	imports := map[string]bool{
		"BoundNotification": true,
		"BoundRequest":      true,
		"BoundResponse":     true,
	}
	for _, fixtureCase := range fixture.Cases {
		for _, name := range []string{fixtureCase.ParamsType, fixtureCase.ResultType, fixtureCase.PayloadType} {
			if name != "" {
				imports[name] = true
			}
		}
	}
	importNames := make([]string, 0, len(imports))
	for name := range imports {
		importNames = append(importNames, name)
	}
	sort.Strings(importNames)

	var out bytes.Buffer
	out.WriteString(typeScriptGeneratedHeader)
	out.WriteString("import type {\n")
	for _, name := range importNames {
		fmt.Fprintf(&out, "  %s,\n", name)
	}
	out.WriteString("} from \"../gollem_appserver_protocol\";\n\n")
	fmt.Fprintf(&out, "export const fixtureProtocolVersion = %s as const;\n", typeScriptString(fixture.ProtocolVersion))
	fmt.Fprintf(&out, "export const fixtureSchemaVersion = %s as const;\n\n", typeScriptString(fixture.SchemaVersion))

	seen := make(map[string]bool, len(fixture.Cases))
	hasInitialize := false
	hasInitialized := false
	hasFilesystem := false
	for _, fixtureCase := range fixture.Cases {
		identifier := typeScriptIdentifier(fixtureCase.Name)
		if identifier == "" || seen[identifier] {
			return nil, fmt.Errorf("invalid or duplicate fixture identifier for %q", fixtureCase.Name)
		}
		seen[identifier] = true
		info, ok := LookupMethod(fixtureCase.Method)
		if !ok || info.Surface != fixtureCase.Surface {
			return nil, fmt.Errorf("fixture %s references invalid method surface %s/%s", fixtureCase.Name, fixtureCase.Surface, fixtureCase.Method)
		}
		if !typeScriptFixtureBindingExists(fixtureCase) {
			return nil, fmt.Errorf("fixture %s type metadata is not bound to %s", fixtureCase.Name, fixtureCase.Method)
		}
		hasInitialize = hasInitialize || fixtureCase.Method == "initialize"
		hasInitialized = hasInitialized || fixtureCase.Method == "initialized"
		hasFilesystem = hasFilesystem || strings.HasPrefix(fixtureCase.Method, "fs/")

		var message bytes.Buffer
		if err := json.Indent(&message, fixtureCase.Message, "", "  "); err != nil {
			return nil, fmt.Errorf("format fixture %s: %w", fixtureCase.Name, err)
		}
		envelope, err := typeScriptFixtureEnvelope(fixtureCase)
		if err != nil {
			return nil, fmt.Errorf("fixture %s: %w", fixtureCase.Name, err)
		}
		bindingType := ""
		switch envelope {
		case "notification":
			bindingType = "BoundNotification<" + typeScriptString(fixtureCase.Method) + ">"
		case "request":
			bindingType = "BoundRequest<" + typeScriptString(fixtureCase.Method) + ">"
		case "response":
			bindingType = "BoundResponse<" + typeScriptString(fixtureCase.Method) + ">"
		}
		fmt.Fprintf(&out, "export const %s = %s satisfies %s;\n", identifier, message.String(), bindingType)
		if fixtureCase.ParamsType != "" {
			fmt.Fprintf(&out, "export const %sParams = %s.params satisfies %s;\n", identifier, identifier, fixtureCase.ParamsType)
		}
		if fixtureCase.ResultType != "" {
			fmt.Fprintf(&out, "export const %sResult = %s.result satisfies %s;\n", identifier, identifier, fixtureCase.ResultType)
		}
		if fixtureCase.PayloadType != "" {
			payload, err := typeScriptFixturePayload(fixtureCase.Message)
			if err != nil {
				return nil, fmt.Errorf("fixture %s payload: %w", fixtureCase.Name, err)
			}
			fmt.Fprintf(&out, "export const %sPayload = %s satisfies %s;\n", identifier, payload, fixtureCase.PayloadType)
		}
		out.WriteByte('\n')
	}
	out.WriteString("// @ts-expect-error request methods cannot use notification envelopes.\n")
	out.WriteString("export type RejectRequestAsNotification = BoundNotification<\"daemon/status\">;\n")
	out.WriteString("// @ts-expect-error notification methods cannot use request envelopes.\n")
	out.WriteString("export type RejectNotificationAsRequest = BoundRequest<\"item/started\">;\n")
	if hasInitialize {
		out.WriteString("// @ts-expect-error initialize requires clientInfo.\n")
		out.WriteString("export const rejectInitializeWithoutClientInfo = { \"capabilities\": {} } satisfies InitializeParams;\n")
		out.WriteString("// @ts-expect-error initialize requires clientInfo.version.\n")
		out.WriteString("export const rejectInitializeWithoutClientVersion = { \"clientInfo\": { \"name\": \"client\" } } satisfies InitializeParams;\n")
	}
	if hasInitialized {
		out.WriteString("// @ts-expect-error initialized does not accept params.\n")
		out.WriteString("export const rejectInitializedParams = { \"method\": \"initialized\", \"params\": {} } satisfies BoundNotification<\"initialized\">;\n")
	}
	if hasFilesystem {
		out.WriteString("// @ts-expect-error public writes require base64 data.\n")
		out.WriteString("export const rejectFilesystemWriteWithoutData = { path: \"/workspace/file\" } satisfies FsWriteFileParams;\n")
		out.WriteString("// @ts-expect-error copy recursive is non-null when present.\n")
		out.WriteString("export const rejectFilesystemCopyNullRecursive = { sourcePath: \"/workspace/a\", destinationPath: \"/workspace/b\", recursive: null } satisfies FsCopyParams;\n")
		out.WriteString("// @ts-expect-error directory responses require a non-null entries array.\n")
		out.WriteString("export const rejectFilesystemNullEntries = { entries: null } satisfies FsReadDirectoryResponse;\n")
		out.WriteString("// @ts-expect-error watch notifications require changedPaths.\n")
		out.WriteString("export const rejectFilesystemChangedWithoutPaths = { watchId: \"watch\" } satisfies FsChangedNotification;\n")
		out.WriteString("// @ts-expect-error metadata responses require every public field.\n")
		out.WriteString("export const rejectFilesystemPartialMetadata = { isFile: true } satisfies FsGetMetadataResponse;\n")
	}
	return out.Bytes(), nil
}

func typeScriptFixtureEnvelope(fixtureCase typeScriptFixtureCase) (string, error) {
	envelope := fixtureCase.Envelope
	if envelope == "" {
		switch fixtureCase.Surface {
		case SurfaceServerNotification, SurfaceClientNotification:
			envelope = "notification"
		case SurfaceServerRequest, SurfaceClientRequest:
			envelope = "request"
		case SurfaceGollemExtension:
			envelope = "response"
		}
	}

	valid := false
	switch envelope {
	case "notification":
		valid = fixtureCase.Surface == SurfaceServerNotification || fixtureCase.Surface == SurfaceClientNotification
	case "request", "response":
		valid = fixtureCase.Surface == SurfaceClientRequest || fixtureCase.Surface == SurfaceServerRequest || fixtureCase.Surface == SurfaceGollemExtension
	default:
		return "", fmt.Errorf("unsupported envelope %q", envelope)
	}
	if !valid {
		return "", fmt.Errorf("envelope %q is incompatible with surface %q", envelope, fixtureCase.Surface)
	}
	return envelope, nil
}

func typeScriptFixturePayload(message json.RawMessage) (string, error) {
	var envelope struct {
		Params struct {
			Item struct {
				Payload json.RawMessage `json:"payload"`
			} `json:"item"`
		} `json:"params"`
	}
	if err := json.Unmarshal(message, &envelope); err != nil {
		return "", err
	}
	if len(envelope.Params.Item.Payload) == 0 {
		return "", errors.New("params.item.payload is missing")
	}
	var formatted bytes.Buffer
	if err := json.Indent(&formatted, envelope.Params.Item.Payload, "", "  "); err != nil {
		return "", err
	}
	return formatted.String(), nil
}

func typeScriptFixtureBindingExists(fixtureCase typeScriptFixtureCase) bool {
	for _, binding := range WireTypeBindings() {
		if binding.Method != fixtureCase.Method || binding.Surface != fixtureCase.Surface {
			continue
		}
		if fixtureCase.ParamsType != "" && !stringSliceContains(binding.Params, fixtureCase.ParamsType) {
			return false
		}
		if fixtureCase.ResultType != "" && !stringSliceContains(binding.Result, fixtureCase.ResultType) {
			return false
		}
		if fixtureCase.PayloadType != "" {
			for _, payloadBinding := range ItemPayloadBindings() {
				if payloadBinding.Type == fixtureCase.PayloadType {
					return true
				}
			}
			return false
		}
		return true
	}
	return false
}

func stringSliceContains(values []string, want string) bool {
	for _, value := range values {
		if value == want {
			return true
		}
	}
	return false
}

func typeScriptIdentifier(value string) string {
	var out strings.Builder
	upperNext := false
	for i, r := range value {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			upperNext = out.Len() > 0
			continue
		}
		if out.Len() == 0 {
			if unicode.IsDigit(r) {
				out.WriteByte('_')
			}
			out.WriteRune(unicode.ToLower(r))
			continue
		}
		if upperNext {
			r = unicode.ToUpper(r)
			upperNext = false
		} else if i == 0 {
			r = unicode.ToLower(r)
		}
		out.WriteRune(r)
	}
	return out.String()
}
